// Generated by Flutter gen-l10n. Do not edit.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'GixGiz';

  @override
  String get appMarkSemanticLabel => 'GixGiz application mark';

  @override
  String get foundationNavigationLabel => 'Foundation';

  @override
  String get aboutNavigationLabel => 'About';

  @override
  String get foundationTitle => 'Foundation';

  @override
  String get aboutTitle => 'About GixGiz';

  @override
  String get loadingTitle => 'Checking foundation';

  @override
  String get loadingMessage =>
      'GixGiz is checking whether the local core is available.';

  @override
  String get coreReadyTitle => 'Platform core ready';

  @override
  String get coreReadyMessage =>
      'The authenticated Rust platform core is available.';

  @override
  String get notConnectedTitle => 'Core not connected';

  @override
  String get notConnectedMessage =>
      'The local platform core is unavailable. Check again before continuing.';

  @override
  String get missingCoreTitle => 'Core component missing';

  @override
  String get missingCoreMessage =>
      'The bundled Rust core could not be found. Repair or reinstall GixGiz, then try again.';

  @override
  String get startupTimedOutTitle => 'Core startup timed out';

  @override
  String get startupTimedOutMessage =>
      'The local core did not complete its secure startup in time. Close GixGiz and try again.';

  @override
  String get connectionLostTitle => 'Core connection lost';

  @override
  String get connectionLostMessage =>
      'The authenticated local connection ended unexpectedly. Check again to reconnect.';

  @override
  String get protocolMismatchTitle => 'Core update required';

  @override
  String get protocolMismatchMessage =>
      'The desktop and bundled core use incompatible protocol versions. Repair or update GixGiz.';

  @override
  String get authenticationFailedTitle => 'Core authentication failed';

  @override
  String get authenticationFailedMessage =>
      'The secure local session could not be authenticated. Restart GixGiz to create a new session.';

  @override
  String get degradedTitle => 'Core connection degraded';

  @override
  String get degradedMessage =>
      'The desktop received a limited core status. Check again before continuing.';

  @override
  String get failedTitle => 'Foundation check failed';

  @override
  String get failedMessage =>
      'GixGiz could not check the local core. Review diagnostics, then try again.';

  @override
  String get cancelledTitle => 'Foundation check cancelled';

  @override
  String get cancelledMessage =>
      'The check was cancelled. No system changes were made.';

  @override
  String get checkAgainAction => 'Check again';

  @override
  String get diagnosticsLabel => 'Diagnostics';

  @override
  String diagnosticCodeLabel(String code) {
    return 'Diagnostic code: $code';
  }

  @override
  String foundationStatusSemanticLabel(String status, String detail) {
    return 'Foundation status: $status. $detail';
  }

  @override
  String get loadingProgressSemanticLabel => 'Foundation check progress';

  @override
  String get inProgressSemanticValue => 'In progress';

  @override
  String get coreApplicationLabel => 'Application';

  @override
  String get coreVersionLabel => 'Core version';

  @override
  String get protocolVersionLabel => 'Protocol';

  @override
  String get readinessLabel => 'Readiness';

  @override
  String get unknownValue => 'Unknown';

  @override
  String coreDetailsSemanticLabel(
    String application,
    String version,
    String protocol,
    String readiness,
  ) {
    return 'Core details: application $application, version $version, protocol $protocol, readiness $readiness';
  }

  @override
  String get aboutSummary => 'Local-first desktop foundation';

  @override
  String get releaseLabel => 'Release';

  @override
  String get applicationIdLabel => 'Application ID';

  @override
  String get coreConnectionLabel => 'Local core';

  @override
  String get coreNotConnectedValue => 'Not connected in this build';

  @override
  String get hardwareScanIdleTitle => 'Hardware evidence';

  @override
  String get hardwareScanIdleMessage =>
      'Scan this PC for local OS, processor, physical memory, display adapter, acceleration, and storage evidence.';

  @override
  String get hardwareScanLoadingTitle => 'Scanning hardware';

  @override
  String get hardwareScanLoadingMessage =>
      'GixGiz is collecting bounded, non-elevated Windows evidence.';

  @override
  String get hardwareScanReadyTitle => 'Hardware evidence ready';

  @override
  String get hardwareScanReadyMessage =>
      'All requested evidence was reported reliably.';

  @override
  String get hardwareScanPartialTitle =>
      'Hardware evidence partially available';

  @override
  String get hardwareScanPartialMessage =>
      'The profile is usable, and unavailable values remain explicitly unknown.';

  @override
  String get hardwareScanFailedTitle => 'Hardware scan failed';

  @override
  String get hardwareScanFailedMessage =>
      'GixGiz could not produce a usable hardware profile. Review diagnostics, then try again.';

  @override
  String get hardwareScanCancelledTitle => 'Hardware scan cancelled';

  @override
  String get hardwareScanCancelledMessage =>
      'The scan stopped without changing system settings.';

  @override
  String get hardwareScanStartAction => 'Scan hardware';

  @override
  String get hardwareScanAgainAction => 'Scan again';

  @override
  String get hardwareScanCancelAction => 'Cancel scan';

  @override
  String get hardwareScanProgressSemanticLabel =>
      'Hardware evidence scan progress';

  @override
  String hardwareScanStatusSemanticLabel(String status, String detail) {
    return 'Hardware scan status: $status. $detail';
  }

  @override
  String hardwareProfileSemanticLabel(String completeness, int version) {
    return 'Hardware profile $completeness, schema version $version';
  }

  @override
  String get hardwareOperatingSystemLabel => 'Operating system';

  @override
  String get hardwareCpuLabel => 'Processor';

  @override
  String get hardwarePhysicalMemoryLabel => 'Physical memory';

  @override
  String get hardwareGpuLabel => 'Display adapter';

  @override
  String hardwareGpuNumberLabel(int number) {
    return 'Display adapter $number';
  }

  @override
  String get hardwareAccelerationLabel => 'Acceleration evidence';

  @override
  String get hardwareStorageLabel => 'Application storage';

  @override
  String hardwareOperatingSystemValue(
    String name,
    String version,
    String architecture,
  ) {
    return '$name, version $version, $architecture';
  }

  @override
  String hardwareCpuValue(String name, String physical, String logical) {
    return '$name, $physical physical cores, $logical logical processors';
  }

  @override
  String hardwareMemoryValue(String total, String available) {
    return '$total total, $available available';
  }

  @override
  String hardwareGpuValue(String name, String dedicated, String shared) {
    return '$name, dedicated memory $dedicated, shared memory $shared';
  }

  @override
  String hardwareAccelerationValue(String kind, String support) {
    return '$kind: $support';
  }

  @override
  String hardwareStorageValue(
    String capacity,
    String free,
    String filesystem,
    String media,
  ) {
    return '$capacity capacity, $free free, $filesystem, $media';
  }

  @override
  String hardwareEvidenceDetail(String source, String reason) {
    return 'Source: $source. $reason';
  }

  @override
  String get supportedValue => 'Supported';

  @override
  String get notSupportedValue => 'Not supported';

  @override
  String get capabilityTitle => 'Plan for this PC';

  @override
  String get capabilityWorkloadLabel => 'Primary use';

  @override
  String get capabilityWorkloadGeneral => 'Writing and chat';

  @override
  String get capabilityWorkloadCoding => 'Coding';

  @override
  String get capabilityPriorityLabel => 'Preference';

  @override
  String get capabilityPriorityBalanced => 'Balanced';

  @override
  String get capabilityPriorityFastest => 'Fastest setup';

  @override
  String get capabilityPriorityLightest => 'Lowest resource use';

  @override
  String get capabilityPriorityQuality => 'Best quality within safe limits';

  @override
  String get capabilityLargerOptionLabel => 'Show a larger safe option';

  @override
  String get capabilityGenerateAction => 'Generate plan';

  @override
  String get capabilityProgressSemanticLabel => 'Capability planning progress';

  @override
  String get capabilityIdleMessage =>
      'No plan has been generated for this hardware profile.';

  @override
  String get capabilityIdleSemanticLabel => 'Capability plan not generated';

  @override
  String get capabilityLoadingMessage => 'Checking safe options for this PC.';

  @override
  String get capabilityLoadingSemanticLabel =>
      'Capability planning in progress';

  @override
  String capabilityReadySemanticLabel(String name, String confidence) {
    return 'Recommended plan: $name. Confidence: $confidence.';
  }

  @override
  String get capabilityRecommendedTitle => 'Recommended';

  @override
  String get capabilityFallbackTitle => 'Smaller fallback';

  @override
  String get capabilityLargerTitle => 'Larger option';

  @override
  String get capabilityMemoryLabel => 'Memory allowance';

  @override
  String get capabilityStorageEstimateLabel => 'Storage allowance';

  @override
  String get capabilityModeLabel => 'Operating mode';

  @override
  String get capabilityStandardMode => 'Standard';

  @override
  String get capabilityAcceleratedMode => 'Accelerated';

  @override
  String get capabilityConfidenceLabel => 'Confidence';

  @override
  String get capabilityConfidenceHigh => 'High';

  @override
  String get capabilityConfidenceMedium => 'Medium';

  @override
  String get capabilityConfidenceLow => 'Low';

  @override
  String get capabilityReasonsLabel => 'Why this result';

  @override
  String get capabilityWarningsLabel => 'Important considerations';

  @override
  String capabilityLicenceLabel(String licence) {
    return 'Licence: $licence';
  }

  @override
  String capabilitySourceLabel(String source) {
    return 'Source: $source';
  }

  @override
  String capabilityVersionsLabel(String catalogue, String rules) {
    return 'Catalogue $catalogue; rules $rules';
  }

  @override
  String get capabilityNoPlanTitle => 'No safe plan available';

  @override
  String get capabilityNoPlanMessage =>
      'The current evidence or available resources do not support a safe plan.';

  @override
  String get capabilityNoPlanSemanticLabel =>
      'No safe capability plan is available';

  @override
  String get capabilityFailedTitle => 'Planning failed';

  @override
  String get capabilityFailedMessage =>
      'GixGiz could not generate a plan. Review diagnostics, then try again.';

  @override
  String get capabilityFailedSemanticLabel => 'Capability planning failed';
}
