// Generated by Flutter gen-l10n. Do not edit.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'GixGiz';

  @override
  String get appMarkSemanticLabel => 'GixGiz application mark';

  @override
  String get foundationNavigationLabel => 'Foundation';

  @override
  String get aboutNavigationLabel => 'About';

  @override
  String get foundationTitle => 'Foundation';

  @override
  String get aboutTitle => 'About GixGiz';

  @override
  String get loadingTitle => 'Checking foundation';

  @override
  String get loadingMessage =>
      'GixGiz is checking whether the local core is available.';

  @override
  String get coreReadyTitle => 'Platform core ready';

  @override
  String get coreReadyMessage =>
      'The authenticated Rust platform core is available.';

  @override
  String get notConnectedTitle => 'Core not connected';

  @override
  String get notConnectedMessage =>
      'The local platform core is unavailable. Check again before continuing.';

  @override
  String get missingCoreTitle => 'Core component missing';

  @override
  String get missingCoreMessage =>
      'The bundled Rust core could not be found. Repair or reinstall GixGiz, then try again.';

  @override
  String get startupTimedOutTitle => 'Core startup timed out';

  @override
  String get startupTimedOutMessage =>
      'The local core did not complete its secure startup in time. Close GixGiz and try again.';

  @override
  String get connectionLostTitle => 'Core connection lost';

  @override
  String get connectionLostMessage =>
      'The authenticated local connection ended unexpectedly. Check again to reconnect.';

  @override
  String get protocolMismatchTitle => 'Core update required';

  @override
  String get protocolMismatchMessage =>
      'The desktop and bundled core use incompatible protocol versions. Repair or update GixGiz.';

  @override
  String get authenticationFailedTitle => 'Core authentication failed';

  @override
  String get authenticationFailedMessage =>
      'The secure local session could not be authenticated. Restart GixGiz to create a new session.';

  @override
  String get degradedTitle => 'Core connection degraded';

  @override
  String get degradedMessage =>
      'The desktop received a limited core status. Check again before continuing.';

  @override
  String get failedTitle => 'Foundation check failed';

  @override
  String get failedMessage =>
      'GixGiz could not check the local core. Review diagnostics, then try again.';

  @override
  String get cancelledTitle => 'Foundation check cancelled';

  @override
  String get cancelledMessage =>
      'The check was cancelled. No system changes were made.';

  @override
  String get checkAgainAction => 'Check again';

  @override
  String get diagnosticsLabel => 'Diagnostics';

  @override
  String diagnosticCodeLabel(String code) {
    return 'Diagnostic code: $code';
  }

  @override
  String foundationStatusSemanticLabel(String status, String detail) {
    return 'Foundation status: $status. $detail';
  }

  @override
  String get loadingProgressSemanticLabel => 'Foundation check progress';

  @override
  String get inProgressSemanticValue => 'In progress';

  @override
  String get coreApplicationLabel => 'Application';

  @override
  String get coreVersionLabel => 'Core version';

  @override
  String get protocolVersionLabel => 'Protocol';

  @override
  String get readinessLabel => 'Readiness';

  @override
  String get unknownValue => 'Unknown';

  @override
  String coreDetailsSemanticLabel(
    String application,
    String version,
    String protocol,
    String readiness,
  ) {
    return 'Core details: application $application, version $version, protocol $protocol, readiness $readiness';
  }

  @override
  String get aboutSummary => 'Local-first desktop foundation';

  @override
  String get releaseLabel => 'Release';

  @override
  String get applicationIdLabel => 'Application ID';

  @override
  String get coreConnectionLabel => 'Local core';

  @override
  String get coreNotConnectedValue => 'Not connected in this build';

  @override
  String get hardwareScanIdleTitle => 'Hardware evidence';

  @override
  String get hardwareScanIdleMessage =>
      'Scan this PC for local OS, processor, physical memory, display adapter, acceleration, and storage evidence.';

  @override
  String get hardwareScanLoadingTitle => 'Scanning hardware';

  @override
  String get hardwareScanLoadingMessage =>
      'GixGiz is collecting bounded, non-elevated Windows evidence.';

  @override
  String get hardwareScanReadyTitle => 'Hardware evidence ready';

  @override
  String get hardwareScanReadyMessage =>
      'All requested evidence was reported reliably.';

  @override
  String get hardwareScanPartialTitle =>
      'Hardware evidence partially available';

  @override
  String get hardwareScanPartialMessage =>
      'The profile is usable, and unavailable values remain explicitly unknown.';

  @override
  String get hardwareScanFailedTitle => 'Hardware scan failed';

  @override
  String get hardwareScanFailedMessage =>
      'GixGiz could not produce a usable hardware profile. Review diagnostics, then try again.';

  @override
  String get hardwareScanCancelledTitle => 'Hardware scan cancelled';

  @override
  String get hardwareScanCancelledMessage =>
      'The scan stopped without changing system settings.';

  @override
  String get hardwareScanStartAction => 'Scan hardware';

  @override
  String get hardwareScanAgainAction => 'Scan again';

  @override
  String get hardwareScanCancelAction => 'Cancel scan';

  @override
  String get hardwareScanProgressSemanticLabel =>
      'Hardware evidence scan progress';

  @override
  String hardwareScanStatusSemanticLabel(String status, String detail) {
    return 'Hardware scan status: $status. $detail';
  }

  @override
  String hardwareProfileSemanticLabel(String completeness, int version) {
    return 'Hardware profile $completeness, schema version $version';
  }

  @override
  String get hardwareOperatingSystemLabel => 'Operating system';

  @override
  String get hardwareCpuLabel => 'Processor';

  @override
  String get hardwarePhysicalMemoryLabel => 'Physical memory';

  @override
  String get hardwareGpuLabel => 'Display adapter';

  @override
  String hardwareGpuNumberLabel(int number) {
    return 'Display adapter $number';
  }

  @override
  String get hardwareAccelerationLabel => 'Acceleration evidence';

  @override
  String get hardwareStorageLabel => 'Application storage';

  @override
  String hardwareOperatingSystemValue(
    String name,
    String version,
    String architecture,
  ) {
    return '$name, version $version, $architecture';
  }

  @override
  String hardwareCpuValue(String name, String physical, String logical) {
    return '$name, $physical physical cores, $logical logical processors';
  }

  @override
  String hardwareMemoryValue(String total, String available) {
    return '$total total, $available available';
  }

  @override
  String hardwareGpuValue(String name, String dedicated, String shared) {
    return '$name, dedicated memory $dedicated, shared memory $shared';
  }

  @override
  String hardwareAccelerationValue(String kind, String support) {
    return '$kind: $support';
  }

  @override
  String hardwareStorageValue(
    String capacity,
    String free,
    String filesystem,
    String media,
  ) {
    return '$capacity capacity, $free free, $filesystem, $media';
  }

  @override
  String hardwareEvidenceDetail(String source, String reason) {
    return 'Source: $source. $reason';
  }

  @override
  String get supportedValue => 'Supported';

  @override
  String get notSupportedValue => 'Not supported';

  @override
  String get capabilityTitle => 'Plan for this PC';

  @override
  String get capabilityWorkloadLabel => 'Primary use';

  @override
  String get capabilityWorkloadGeneral => 'Writing and chat';

  @override
  String get capabilityWorkloadCoding => 'Coding';

  @override
  String get capabilityPriorityLabel => 'Preference';

  @override
  String get capabilityPriorityBalanced => 'Balanced';

  @override
  String get capabilityPriorityFastest => 'Fastest setup';

  @override
  String get capabilityPriorityLightest => 'Lowest resource use';

  @override
  String get capabilityPriorityQuality => 'Best quality within safe limits';

  @override
  String get capabilityLargerOptionLabel => 'Show a larger safe option';

  @override
  String get capabilityGenerateAction => 'Generate plan';

  @override
  String get capabilityProgressSemanticLabel => 'Capability planning progress';

  @override
  String get capabilityIdleMessage =>
      'No plan has been generated for this hardware profile.';

  @override
  String get capabilityIdleSemanticLabel => 'Capability plan not generated';

  @override
  String get capabilityLoadingMessage => 'Checking safe options for this PC.';

  @override
  String get capabilityLoadingSemanticLabel =>
      'Capability planning in progress';

  @override
  String capabilityReadySemanticLabel(String name, String confidence) {
    return 'Recommended plan: $name. Confidence: $confidence.';
  }

  @override
  String get capabilityRecommendedTitle => 'Recommended';

  @override
  String get capabilityFallbackTitle => 'Smaller fallback';

  @override
  String get capabilityLargerTitle => 'Larger option';

  @override
  String get capabilityMemoryLabel => 'Memory allowance';

  @override
  String get capabilityStorageEstimateLabel => 'Storage allowance';

  @override
  String get capabilityModeLabel => 'Operating mode';

  @override
  String get capabilityStandardMode => 'Standard';

  @override
  String get capabilityAcceleratedMode => 'Accelerated';

  @override
  String get capabilityConfidenceLabel => 'Confidence';

  @override
  String get capabilityConfidenceHigh => 'High';

  @override
  String get capabilityConfidenceMedium => 'Medium';

  @override
  String get capabilityConfidenceLow => 'Low';

  @override
  String get capabilityReasonsLabel => 'Why this result';

  @override
  String get capabilityWarningsLabel => 'Important considerations';

  @override
  String capabilityLicenceLabel(String licence) {
    return 'Licence: $licence';
  }

  @override
  String capabilitySourceLabel(String source) {
    return 'Source: $source';
  }

  @override
  String capabilityVersionsLabel(String catalogue, String rules) {
    return 'Catalogue $catalogue; rules $rules';
  }

  @override
  String get capabilityNoPlanTitle => 'No safe plan available';

  @override
  String get capabilityNoPlanMessage =>
      'The current evidence or available resources do not support a safe plan.';

  @override
  String get capabilityNoPlanSemanticLabel =>
      'No safe capability plan is available';

  @override
  String get capabilityFailedTitle => 'Planning failed';

  @override
  String get capabilityFailedMessage =>
      'GixGiz could not generate a plan. Review diagnostics, then try again.';

  @override
  String get capabilityFailedSemanticLabel => 'Capability planning failed';

  @override
  String get runtimeTitle => 'Local runtime';

  @override
  String get runtimeIdleTitle => 'Runtime not checked';

  @override
  String get runtimeIdleMessage =>
      'Check for a compatible local runtime before continuing.';

  @override
  String get runtimeCheckingTitle => 'Checking runtime';

  @override
  String get runtimeCheckingMessage =>
      'GixGiz is checking local runtime evidence without changing the installation.';

  @override
  String get runtimeNotInstalledTitle => 'Runtime not installed';

  @override
  String get runtimeNotInstalledMessage =>
      'No compatible local runtime was verified. Installation is not available in this step.';

  @override
  String get runtimeInstalledStoppedTitle => 'Runtime installed but stopped';

  @override
  String get runtimeInstalledStoppedMessage =>
      'A compatible local runtime was found, but it is not ready.';

  @override
  String get runtimeStartingTitle => 'Runtime starting';

  @override
  String get runtimeStartingMessage =>
      'The approved local runtime start is in progress.';

  @override
  String get runtimeReadyTitle => 'Runtime ready';

  @override
  String get runtimeReadyMessage =>
      'The local endpoint, version, and health checks succeeded.';

  @override
  String get runtimeDegradedTitle => 'Runtime needs attention';

  @override
  String get runtimeDegradedMessage =>
      'The runtime responded, but some health or capability evidence is limited.';

  @override
  String get runtimeIncompatibleTitle => 'Runtime version incompatible';

  @override
  String get runtimeIncompatibleMessage =>
      'The detected runtime version is not supported by this GixGiz release.';

  @override
  String get runtimeUpdatingTitle => 'Runtime updating';

  @override
  String get runtimeUpdatingMessage =>
      'An external update is in progress. GixGiz will not change it automatically.';

  @override
  String get runtimeFailedTitle => 'Runtime check failed';

  @override
  String get runtimeFailedMessage =>
      'GixGiz could not obtain a safe runtime status. Review diagnostics, then try again.';

  @override
  String get runtimeUnknownTitle => 'Runtime status unknown';

  @override
  String get runtimeUnknownMessage =>
      'The runtime reported a state this desktop does not recognize. Update GixGiz before continuing.';

  @override
  String get runtimeOperationTitle => 'Runtime operation in progress';

  @override
  String get runtimeOperationMessage =>
      'GixGiz is waiting for the approved operation to reach a verified terminal state.';

  @override
  String runtimeOperationFailedTitle(String operation) {
    return 'Runtime $operation failed';
  }

  @override
  String runtimeOperationFailedMessage(String operation) {
    return 'GixGiz could not complete the approved $operation operation. Review diagnostics and the recommended action.';
  }

  @override
  String get runtimeOperationKindStart => 'start';

  @override
  String get runtimeOperationKindStop => 'stop';

  @override
  String get runtimeOperationKindRestart => 'restart';

  @override
  String get runtimeOperationKindUnknown => 'lifecycle operation';

  @override
  String get runtimeCancelledTitle => 'Runtime operation cancelled';

  @override
  String get runtimeCancelledMessage =>
      'The operation was cancelled. Check the current runtime status before continuing.';

  @override
  String get runtimeProviderLabel => 'Runtime';

  @override
  String get runtimeVersionLabel => 'Version';

  @override
  String get runtimeOwnershipLabel => 'Ownership';

  @override
  String get runtimeReuseConsentLabel => 'Reuse permission';

  @override
  String get runtimeManagementConsentLabel => 'Management permission';

  @override
  String get runtimeEndpointLabel => 'Local endpoint';

  @override
  String get runtimeOwnershipExternal => 'Installed outside GixGiz';

  @override
  String get runtimeOwnershipManaged => 'Managed by GixGiz';

  @override
  String get runtimeOwnershipBundled => 'Included with GixGiz';

  @override
  String get runtimeOwnershipUnknown => 'Ownership not verified';

  @override
  String get runtimeConsentNotRequested => 'Reuse permission not granted';

  @override
  String get runtimeConsentReuseApproved => 'Approved for reuse only';

  @override
  String get runtimeConsentManagementApproved => 'Approved for management';

  @override
  String get runtimeConsentDenied => 'Reuse declined';

  @override
  String get runtimeConsentUnknown => 'Permission state unknown';

  @override
  String get runtimeManagementConsentNotRequested =>
      'Management permission not granted';

  @override
  String get runtimeManagementConsentApproved => 'Approved for management';

  @override
  String get runtimeManagementConsentDenied => 'Management declined';

  @override
  String get runtimeManagementConsentUnknown => 'Management permission unknown';

  @override
  String get runtimeEndpointVerified => 'Verified local endpoint';

  @override
  String get runtimeEndpointRejected => 'Endpoint rejected';

  @override
  String get runtimeEndpointUnknown => 'Endpoint not verified';

  @override
  String get runtimeExternalNotice =>
      'This installation remains externally owned. Reuse does not let GixGiz update, uninstall, reconfigure, or claim it.';

  @override
  String get runtimeManagementRequiredNotice =>
      'Start, stop, and restart remain unavailable because management permission is separate from reuse.';

  @override
  String get runtimeExternalManagementRequiredNotice =>
      'Start, stop, and restart remain unavailable because management permission is separate from reuse. Manage this external installation with its existing controls.';

  @override
  String get runtimeConsentPromptTitle => 'Allow runtime reuse?';

  @override
  String get runtimeConsentPromptMessage =>
      'Allowing reuse lets GixGiz check this local runtime and list its installed models when current health and compatibility evidence permits. Ownership stays external, and this does not approve updates, uninstallation, reconfiguration, or other system changes.';

  @override
  String get runtimeConsentApproveAction => 'Allow reuse';

  @override
  String get runtimeConsentCancelAction => 'Not now';

  @override
  String get runtimeRefreshAction => 'Check runtime';

  @override
  String get runtimeStartAction => 'Start runtime';

  @override
  String get runtimeStopAction => 'Stop runtime';

  @override
  String get runtimeRestartAction => 'Restart runtime';

  @override
  String get runtimeCancelAction => 'Cancel operation';

  @override
  String get runtimeModelsAction => 'Show installed models';

  @override
  String get runtimeModelsHideAction => 'Hide installed models';

  @override
  String get runtimeModelsTitle => 'Installed models';

  @override
  String get runtimeModelsProgressSemanticLabel =>
      'Installed model inventory progress';

  @override
  String get runtimeModelsEmpty => 'No installed models were reported.';

  @override
  String get runtimeModelsFailedMessage =>
      'GixGiz could not list installed models. Review diagnostics, then try again.';

  @override
  String get runtimeModelsTruncated =>
      'More installed models exist than can be shown safely.';

  @override
  String get runtimeExternalModelLabel => 'External model';

  @override
  String runtimeModelSizeLabel(String size) {
    return 'Size: $size';
  }

  @override
  String runtimeModelCatalogueLabel(String model) {
    return 'Catalogue model: $model';
  }

  @override
  String get runtimeReasonsLabel => 'Status details';

  @override
  String get runtimeWarningsLabel => 'Important considerations';

  @override
  String get runtimeReasonInstallationNotFound =>
      'No supported local runtime installation was found.';

  @override
  String get runtimeReasonExecutableVerified =>
      'The runtime executable location was verified.';

  @override
  String get runtimeReasonEndpointUnavailable =>
      'The local runtime endpoint did not respond.';

  @override
  String get runtimeReasonEndpointReachable =>
      'The local runtime endpoint responded.';

  @override
  String get runtimeReasonEndpointUnsafe =>
      'The runtime endpoint was rejected because it was not safely local.';

  @override
  String get runtimeReasonVersionCompatible =>
      'The reported runtime version is compatible.';

  @override
  String get runtimeReasonVersionIncompatible =>
      'The reported runtime version is incompatible.';

  @override
  String get runtimeReasonVersionUnverified =>
      'The runtime version could not be verified.';

  @override
  String get runtimeReasonEvidenceIncomplete =>
      'Some runtime health evidence is incomplete.';

  @override
  String get runtimeReasonOwnershipRequired =>
      'GixGiz ownership is required for this operation.';

  @override
  String get runtimeReasonConsentRequired =>
      'Explicit permission is required for this capability.';

  @override
  String get runtimeReasonOperationUnsupported =>
      'This runtime operation is not supported.';

  @override
  String get runtimeReasonProcessExited =>
      'The managed runtime process exited before it became ready.';

  @override
  String get runtimeReasonUnknown =>
      'Additional runtime evidence is not recognized by this GixGiz version.';

  @override
  String get runtimeWarningExternalInstallation =>
      'This runtime is installed and managed outside GixGiz.';

  @override
  String get runtimeWarningEndpointExposure =>
      'The runtime endpoint may be exposed beyond this device.';

  @override
  String get runtimeWarningVersionUntested =>
      'This runtime version has not been verified with this GixGiz release.';

  @override
  String get runtimeWarningPartialEvidence =>
      'Only partial runtime evidence is available.';

  @override
  String get runtimeWarningModelInventoryTruncated =>
      'The installed model list was limited for safe display.';

  @override
  String get runtimeWarningUnknown =>
      'An unrecognized runtime warning was reported.';

  @override
  String runtimeRecommendedAction(String action) {
    return 'Recommended action: $action';
  }

  @override
  String get runtimeRecoveryRetry => 'Try the operation again.';

  @override
  String get runtimeRecoveryRestart =>
      'Restart GixGiz, then check the runtime again.';

  @override
  String get runtimeRecoveryCheckPrerequisites =>
      'Check the runtime prerequisites, then try again.';

  @override
  String get runtimeRecoveryContactSupport =>
      'Contact support with the diagnostic code.';

  @override
  String get runtimeRecoveryNoAction => 'No action is required.';

  @override
  String get runtimeRecoveryUnknown =>
      'Review diagnostics before trying again.';

  @override
  String get runtimeProgressSemanticLabel => 'Runtime operation progress';

  @override
  String runtimeStatusSemanticLabel(
    String status,
    String message,
    String ownership,
    String consent,
  ) {
    return 'Runtime status: $status. $message Ownership: $ownership. Permission: $consent.';
  }

  @override
  String runtimeDetailsSemanticLabel(
    String provider,
    String version,
    String endpoint,
    String ownership,
    String reuseConsent,
    String managementConsent,
  ) {
    return 'Runtime details: $provider, version $version, endpoint $endpoint, ownership $ownership, reuse permission $reuseConsent, management permission $managementConsent.';
  }

  @override
  String get setupTitle => 'Local model setup';

  @override
  String get setupPlanningTitle => 'Preparing setup plan';

  @override
  String get setupPlanningMessage =>
      'GixGiz is validating the selected recommendation and its local effects.';

  @override
  String get setupUpdatingTitle => 'Updating setup status';

  @override
  String get setupUpdatingMessage =>
      'GixGiz is loading the latest persisted setup state.';

  @override
  String get setupPlanReadyTitle => 'Review setup plan';

  @override
  String get setupPlanReadyMessage =>
      'Review the model, storage, licence, resources, and provider effects before continuing.';

  @override
  String get setupAwaitingApprovalTitle => 'Approval required';

  @override
  String get setupAwaitingApprovalMessage =>
      'No model data will be added until you approve this exact plan.';

  @override
  String get setupApprovedTitle => 'Setup approved';

  @override
  String get setupApprovedMessage => 'The approved plan is ready to start.';

  @override
  String get setupPreparingTitle => 'Preparing model setup';

  @override
  String get setupPreparingMessage =>
      'GixGiz is rechecking the runtime and approved setup plan.';

  @override
  String get setupCheckingStorageTitle => 'Checking storage';

  @override
  String get setupCheckingStorageMessage =>
      'GixGiz is checking destination availability and the required safety margin.';

  @override
  String get setupAcquiringTitle => 'Acquiring model';

  @override
  String get setupAcquiringMessage =>
      'The local runtime is acquiring the approved model artifact.';

  @override
  String get setupCancellingTitle => 'Cancellation requested';

  @override
  String get setupCancellingMessage =>
      'GixGiz is waiting for the local runtime to stop safely and report retained effects.';

  @override
  String get setupRegisteringTitle => 'Registering model';

  @override
  String get setupRegisteringMessage =>
      'GixGiz is checking the model registration reported by the runtime.';

  @override
  String get setupVerifyingRuntimeTitle => 'Verifying runtime';

  @override
  String get setupVerifyingRuntimeMessage =>
      'GixGiz is confirming that the local runtime is healthy.';

  @override
  String get setupVerifyingModelTitle => 'Verifying model';

  @override
  String get setupVerifyingModelMessage =>
      'GixGiz is confirming model availability and registration.';

  @override
  String get setupInferenceTitle => 'Testing readiness';

  @override
  String get setupInferenceMessage =>
      'GixGiz is running a fixed, private-content-free readiness check.';

  @override
  String get setupReadyTitle => 'Local model ready';

  @override
  String get setupReadyMessage =>
      'Runtime health, model availability, registration, and bounded inference were verified.';

  @override
  String get setupAttentionTitle => 'Setup needs attention';

  @override
  String get setupAttentionMessage =>
      'Review the recommended action before continuing.';

  @override
  String get setupFailedTitle => 'Model setup failed';

  @override
  String get setupFailedMessage =>
      'The setup stopped safely. Review diagnostics and the recommended action.';

  @override
  String get setupCancelledTitle => 'Model setup cancelled';

  @override
  String get setupCancelledMessage =>
      'The setup stopped after recording completed, retained, rolled-back, and uncertain effects.';

  @override
  String get setupUnknownTitle => 'Setup state needs review';

  @override
  String get setupUnknownMessage =>
      'This GixGiz version does not recognize the reported setup state. No readiness claim was made.';

  @override
  String setupStatusSemanticLabel(
    String status,
    String message,
    String model,
    String stage,
  ) {
    return 'Model setup status: $status. $message Model: $model. Stage: $stage.';
  }

  @override
  String get setupProgressSemanticLabel => 'Model setup progress';

  @override
  String setupProgressPercent(String percent) {
    return '$percent% complete';
  }

  @override
  String setupProgressBytes(String completed, String total) {
    return '$completed of $total';
  }

  @override
  String get setupModelLabel => 'Model';

  @override
  String get setupFamilyLabel => 'Family';

  @override
  String get setupProviderArtifactLabel => 'Provider artifact';

  @override
  String get setupRuntimeLabel => 'Local runtime';

  @override
  String get setupRuntimeVersionLabel => 'Runtime version';

  @override
  String get setupLicenceLabel => 'Licence';

  @override
  String get setupProvenanceLabel => 'Source';

  @override
  String get setupDestinationLabel => 'Destination';

  @override
  String get setupExpectedSizeLabel => 'Expected size';

  @override
  String get setupPlanComponentsLabel => 'Plan components';

  @override
  String get setupComponentRuntime => 'Compatible local runtime';

  @override
  String get setupComponentModel => 'Selected local model';

  @override
  String get setupComponentStorage => 'Approved storage destination';

  @override
  String get setupComponentVerification =>
      'Runtime, model, registration, and inference verification';

  @override
  String get setupComponentUnknown => 'Unrecognized setup component';

  @override
  String setupComponentRequired(String component) {
    return '$component (required)';
  }

  @override
  String setupComponentOptional(String component) {
    return '$component (optional)';
  }

  @override
  String get setupRequiredEffectsLabel => 'This approval allows';

  @override
  String get setupReasonsLabel => 'Why this plan was selected';

  @override
  String get setupReasonRecommendationSelected =>
      'This model comes from the deterministic recommendation shown above.';

  @override
  String get setupReasonExistingModelReusable =>
      'The exact provider model is already available and may be reused.';

  @override
  String get setupReasonAcquisitionRequired =>
      'The selected provider model must be added before verification.';

  @override
  String get setupReasonApprovalRequired =>
      'The listed local effects require approval before setup starts.';

  @override
  String get setupReasonStorageVerified =>
      'Storage was checked with the required safety margin.';

  @override
  String get setupReasonRuntimeVerified =>
      'The compatible local runtime was verified.';

  @override
  String get setupReasonRegistrationVerified =>
      'The exact provider model registration was verified.';

  @override
  String get setupReasonReadinessVerified =>
      'The bounded readiness check was verified.';

  @override
  String get setupReasonUnknown =>
      'The core reported an unrecognized setup reason.';

  @override
  String get setupWarningsLabel => 'Important considerations';

  @override
  String get setupWarningExternalRuntimeModified =>
      'Setup changes an externally managed local runtime without transferring its ownership to GixGiz.';

  @override
  String get setupWarningProviderManagedStorage =>
      'The local runtime owns and controls this model storage.';

  @override
  String get setupWarningIntegrityMetadataUnavailable =>
      'No trusted independent checksum is available for this provider model.';

  @override
  String get setupWarningCancellationMayRetainEffects =>
      'Cancellation may leave provider-owned partial or completed model data in place.';

  @override
  String get setupWarningDestinationEvidenceIncomplete =>
      'Some storage destination evidence could not be verified.';

  @override
  String get setupWarningUnknown =>
      'The core reported an unrecognized setup warning.';

  @override
  String get setupProviderManagedDestination =>
      'Provider-managed local storage';

  @override
  String get setupApplicationDataDestination => 'GixGiz application storage';

  @override
  String get setupUserSelectedDestination => 'Approved user-selected storage';

  @override
  String get setupUnknownDestination => 'Unverified storage destination';

  @override
  String get setupReviewAction => 'Review setup';

  @override
  String get setupApproveAction => 'Approve plan';

  @override
  String get setupDenyAction => 'Decline plan';

  @override
  String get setupApprovalBackAction => 'Not now';

  @override
  String get setupStartAction => 'Start setup';

  @override
  String get setupCancelAction => 'Cancel setup';

  @override
  String get setupKeepRunningAction => 'Keep running';

  @override
  String get setupRetryAction => 'Retry setup';

  @override
  String get setupRefreshAction => 'Refresh status';

  @override
  String get setupApprovalPromptTitle => 'Approve this model setup?';

  @override
  String setupApprovalPromptMessage(
    String model,
    String runtime,
    String size,
    String destination,
  ) {
    return 'Approve adding $model to $runtime. This exact approval covers $size in $destination and only the listed effects.';
  }

  @override
  String get setupCancelPromptTitle => 'Cancel model setup?';

  @override
  String get setupCancelPromptMessage =>
      'Cancellation is cooperative. Provider-owned partial data may be retained and will be reported honestly.';

  @override
  String get setupCancelApprovedPromptMessage =>
      'Cancel this approved setup before it starts. No provider work will begin.';

  @override
  String get setupCancelAttentionPromptMessage =>
      'Cancel this setup after reviewing its attention state. Existing completed, retained, rolled-back, and uncertain effects will remain recorded.';

  @override
  String get setupEffectProviderAcquisition => 'Add provider-owned model data';

  @override
  String get setupEffectProviderRegistration => 'Register the approved model';

  @override
  String get setupEffectReadinessInference => 'Run a bounded readiness check';

  @override
  String get setupEffectMetadataPersistence => 'Store setup and model metadata';

  @override
  String get setupEffectUnknown => 'Unrecognized setup effect';

  @override
  String get setupEffectsTitle => 'Recorded effects';

  @override
  String get setupEffectCompleted => 'Completed';

  @override
  String get setupEffectRetained => 'Retained';

  @override
  String get setupEffectRolledBack => 'Rolled back';

  @override
  String get setupEffectUncertain => 'Uncertain';

  @override
  String get setupEffectDispositionUnknown => 'Unrecognized';

  @override
  String get setupAttentionRuntimeNotInstalled =>
      'The required local runtime is not installed.';

  @override
  String get setupAttentionRuntimeConsentRequired =>
      'Review and approve the local runtime preparation before continuing.';

  @override
  String get setupAttentionRuntimeUnavailable =>
      'The local runtime is currently unavailable.';

  @override
  String get setupAttentionPrivilegedRuntime =>
      'Runtime installation requires a separate privileged approval.';

  @override
  String get setupAttentionDestinationUnavailable =>
      'The approved storage destination is unavailable.';

  @override
  String get setupAttentionInsufficientStorage =>
      'The approved destination does not have enough free storage with the required safety margin.';

  @override
  String get setupAttentionAcquisitionInterrupted =>
      'Model acquisition was interrupted before verification completed.';

  @override
  String get setupAttentionRegistrationUnverified =>
      'The runtime could not verify model registration.';

  @override
  String get setupAttentionModelUnavailable =>
      'The approved model is not available to the runtime.';

  @override
  String get setupAttentionIntegrityMismatch =>
      'The acquired model did not pass integrity verification.';

  @override
  String get setupAttentionReadinessTimedOut =>
      'The bounded readiness check timed out.';

  @override
  String get setupAttentionReadinessFailed =>
      'The runtime or model readiness check did not succeed.';

  @override
  String get setupAttentionRecoveryRequired =>
      'Persisted setup state requires recovery before work can continue.';

  @override
  String get setupAttentionUnknown =>
      'Setup reported an unrecognized attention state. Review diagnostics before continuing.';

  @override
  String get setupRecoveryReviewApproval =>
      'Review and approve the exact current plan.';

  @override
  String get setupRecoveryRetry =>
      'Retry after GixGiz rechecks current conditions.';

  @override
  String get setupRecoveryRestoreDestination =>
      'Reconnect or restore the approved destination.';

  @override
  String get setupRecoveryFreeStorage =>
      'Free storage while preserving the required safety margin.';

  @override
  String get setupRecoveryRestoreRuntime =>
      'Restore the compatible local runtime using its existing controls.';

  @override
  String get setupRecoveryCheckPrerequisites =>
      'Review the local runtime and platform prerequisites.';

  @override
  String get chatNavigationLabel => 'Chat';

  @override
  String get chatTitle => 'Chat';

  @override
  String get chatDescription =>
      'Talk with the local model that GixGiz prepared on this PC.';

  @override
  String get chatLocalityChecking => 'Checking local runtime...';

  @override
  String get chatLocalityUnknown => 'Local status is not verified';

  @override
  String get chatRuntimeUnavailable => 'Local runtime needs attention';

  @override
  String get chatModelUnavailable => 'Local model is not available';

  @override
  String get chatRunningLocally => 'Running locally on this PC';

  @override
  String chatRunningLocallyWithModel(String model) {
    return 'Running locally on this PC with $model';
  }

  @override
  String chatLocalitySemanticLabel(String detail) {
    return 'Chat location: $detail';
  }

  @override
  String get chatNewConversationAction => 'New conversation';

  @override
  String get chatConversationsLoading => 'Loading your conversations';

  @override
  String get chatConversationsEmpty => 'No conversations yet. Start a new one.';

  @override
  String get chatConversationsFailed =>
      'GixGiz could not load your conversations.';

  @override
  String get chatConversationLoading => 'Opening conversation';

  @override
  String get chatRecoveringReply => 'Recovering the active local reply';

  @override
  String get chatNoConversationSelected =>
      'Choose a conversation or start a new one.';

  @override
  String chatMessageCount(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count messages',
      one: '1 message',
      zero: 'No messages',
    );
    return '$_temp0';
  }

  @override
  String get chatRoleUser => 'You';

  @override
  String get chatRoleAssistant => 'Assistant';

  @override
  String get chatComposerLabel => 'Message';

  @override
  String get chatComposerHint => 'Ask the local model something';

  @override
  String get chatSendAction => 'Send';

  @override
  String get chatStopAction => 'Stop';

  @override
  String get chatRetryAction => 'Try again';

  @override
  String get chatReturnToSetupAction => 'Return to setup';

  @override
  String get chatRenameAction => 'Rename conversation';

  @override
  String get chatRenameLabel => 'Conversation name';

  @override
  String get chatDeleteAction => 'Delete conversation';

  @override
  String get chatDeleteActiveTooltip =>
      'Stop the active reply before deleting this conversation';

  @override
  String get chatDeleteConfirmation =>
      'This removes the conversation and its messages from GixGiz. It does not remove the local runtime or the model.';

  @override
  String get chatCancelAction => 'Cancel';

  @override
  String get chatConfirmAction => 'Save';

  @override
  String get chatReplyStreaming => 'Replying...';

  @override
  String get chatReplyStreamingSemanticLabel => 'The assistant is replying';

  @override
  String get chatReplyStopped => 'You stopped this reply, so it is incomplete.';

  @override
  String get chatReplyIncomplete =>
      'This reply did not finish, so it is incomplete.';

  @override
  String get chatAttentionMessage =>
      'GixGiz needs attention before this conversation can continue.';

  @override
  String get chatFailedMessage => 'GixGiz could not complete that chat action.';

  @override
  String get setupRecoveryContactSupport =>
      'Contact support with the diagnostic code.';

  @override
  String get setupRecoveryNoAction => 'No action is required.';

  @override
  String get setupRecoveryUnknown => 'Review diagnostics before continuing.';

  @override
  String setupRecommendedAction(String action) {
    return 'Recommended action: $action';
  }

  @override
  String get runtimeInstallTitle => 'Set up local AI';

  @override
  String get runtimeInstallAvailable =>
      'GixGiz can set up the local AI runtime for you. Nothing is downloaded or changed until you approve the plan.';

  @override
  String get runtimeInstallExternalPresent =>
      'A local AI runtime is already installed on this PC. GixGiz will use it instead of installing another copy.';

  @override
  String get runtimeInstallUnavailable =>
      'Local AI setup is not available on this PC right now.';

  @override
  String get runtimeInstallAwaitingApproval =>
      'Review what this will change, then choose whether to continue.';

  @override
  String get runtimeInstallApproved => 'Approved. Setup has not started yet.';

  @override
  String get runtimeInstallRunning =>
      'Setting up the local AI runtime. You can keep using the rest of GixGiz.';

  @override
  String get runtimeInstallReady =>
      'The local AI runtime is installed and verified.';

  @override
  String get runtimeInstallFailed =>
      'Setup did not finish. Nothing was left half-installed by GixGiz.';

  @override
  String get runtimeInstallCancelled =>
      'Setup was cancelled. Nothing on this PC was changed.';

  @override
  String get runtimeInstallAttention =>
      'Setup needs your attention before it can continue.';

  @override
  String get runtimeInstallReviewAction => 'Review setup';

  @override
  String get runtimeInstallApproveAction => 'Approve and continue';

  @override
  String get runtimeInstallDenyAction => 'Not now';

  @override
  String get runtimeInstallStartAction => 'Start setup';

  @override
  String get runtimeInstallRefreshAction => 'Check progress';

  @override
  String get runtimeInstallComponent => 'What gets installed';

  @override
  String get runtimeInstallVersion => 'Version';

  @override
  String get runtimeInstallSource => 'Downloaded from';

  @override
  String get runtimeInstallPublisher => 'Verified publisher';

  @override
  String get runtimeInstallDownloadSize => 'Download size';

  @override
  String get runtimeInstallAdministrator => 'Administrator needed';

  @override
  String get runtimeInstallAdministratorRequired =>
      'Yes, Windows will ask for permission';

  @override
  String get runtimeInstallAdministratorNotRequired =>
      'No, this installs just for you';

  @override
  String get runtimeVersionAcknowledgeAction => 'Use this version anyway';

  @override
  String get runtimeVersionAcknowledgeTitle =>
      'Use an untested runtime version?';

  @override
  String get runtimeVersionAcknowledgeConfirmAction => 'Accept this version';

  @override
  String runtimeVersionAcknowledgeMessage(String version) {
    return 'GixGiz has not tested version $version. It may still work, but it is outside the versions this release has evidence for. Accepting applies to this exact version only; a later update will ask again.';
  }

  @override
  String runtimeInstallTransferred(
    String transferred,
    String total,
    int percent,
  ) {
    return 'Downloaded $transferred of $total ($percent%)';
  }

  @override
  String runtimeInstallTransferredUnknownTotal(String transferred) {
    return 'Downloaded $transferred';
  }
}
