// Generated by Flutter gen-l10n. Do not edit.
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart' as intl;

import 'app_localizations_en.dart';

// ignore_for_file: type=lint

/// Callers can lookup localized strings with an instance of AppLocalizations
/// returned by `AppLocalizations.of(context)`.
///
/// Applications need to include `AppLocalizations.delegate()` in their app's
/// `localizationDelegates` list, and the locales they support in the app's
/// `supportedLocales` list. For example:
///
/// ```dart
/// import 'l10n/app_localizations.dart';
///
/// return MaterialApp(
///   localizationsDelegates: AppLocalizations.localizationsDelegates,
///   supportedLocales: AppLocalizations.supportedLocales,
///   home: MyApplicationHome(),
/// );
/// ```
///
/// ## Update pubspec.yaml
///
/// Please make sure to update your pubspec.yaml to include the following
/// packages:
///
/// ```yaml
/// dependencies:
///   # Internationalization support.
///   flutter_localizations:
///     sdk: flutter
///   intl: any # Use the pinned version from flutter_localizations
///
///   # Rest of dependencies
/// ```
///
/// ## iOS Applications
///
/// iOS applications define key application metadata, including supported
/// locales, in an Info.plist file that is built into the application bundle.
/// To configure the locales supported by your app, you’ll need to edit this
/// file.
///
/// First, open your project’s ios/Runner.xcworkspace Xcode workspace file.
/// Then, in the Project Navigator, open the Info.plist file under the Runner
/// project’s Runner folder.
///
/// Next, select the Information Property List item, select Add Item from the
/// Editor menu, then select Localizations from the pop-up menu.
///
/// Select and expand the newly-created Localizations item then, for each
/// locale your application supports, add a new item and select the locale
/// you wish to add from the pop-up menu in the Value field. This list should
/// be consistent with the languages listed in the AppLocalizations.supportedLocales
/// property.
abstract class AppLocalizations {
  AppLocalizations(String locale)
    : localeName = intl.Intl.canonicalizedLocale(locale.toString());

  final String localeName;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  /// A list of this localizations delegate along with the default localizations
  /// delegates.
  ///
  /// Returns a list of localizations delegates containing this delegate along with
  /// GlobalMaterialLocalizations.delegate, GlobalCupertinoLocalizations.delegate,
  /// and GlobalWidgetsLocalizations.delegate.
  ///
  /// Additional delegates can be added by appending to this list in
  /// MaterialApp. This list does not have to be used at all if a custom list
  /// of delegates is preferred or required.
  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates =
      <LocalizationsDelegate<dynamic>>[
        delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ];

  /// A list of this localizations delegate's supported locales.
  static const List<Locale> supportedLocales = <Locale>[Locale('en')];

  /// No description provided for @appTitle.
  ///
  /// In en, this message translates to:
  /// **'GixGiz'**
  String get appTitle;

  /// No description provided for @appMarkSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'GixGiz application mark'**
  String get appMarkSemanticLabel;

  /// No description provided for @foundationNavigationLabel.
  ///
  /// In en, this message translates to:
  /// **'Foundation'**
  String get foundationNavigationLabel;

  /// No description provided for @aboutNavigationLabel.
  ///
  /// In en, this message translates to:
  /// **'About'**
  String get aboutNavigationLabel;

  /// No description provided for @foundationTitle.
  ///
  /// In en, this message translates to:
  /// **'Foundation'**
  String get foundationTitle;

  /// No description provided for @aboutTitle.
  ///
  /// In en, this message translates to:
  /// **'About GixGiz'**
  String get aboutTitle;

  /// No description provided for @loadingTitle.
  ///
  /// In en, this message translates to:
  /// **'Checking foundation'**
  String get loadingTitle;

  /// No description provided for @loadingMessage.
  ///
  /// In en, this message translates to:
  /// **'GixGiz is checking whether the local core is available.'**
  String get loadingMessage;

  /// No description provided for @coreReadyTitle.
  ///
  /// In en, this message translates to:
  /// **'Platform core ready'**
  String get coreReadyTitle;

  /// No description provided for @coreReadyMessage.
  ///
  /// In en, this message translates to:
  /// **'The authenticated Rust platform core is available.'**
  String get coreReadyMessage;

  /// No description provided for @notConnectedTitle.
  ///
  /// In en, this message translates to:
  /// **'Core not connected'**
  String get notConnectedTitle;

  /// No description provided for @notConnectedMessage.
  ///
  /// In en, this message translates to:
  /// **'The local platform core is unavailable. Check again before continuing.'**
  String get notConnectedMessage;

  /// No description provided for @missingCoreTitle.
  ///
  /// In en, this message translates to:
  /// **'Core component missing'**
  String get missingCoreTitle;

  /// No description provided for @missingCoreMessage.
  ///
  /// In en, this message translates to:
  /// **'The bundled Rust core could not be found. Repair or reinstall GixGiz, then try again.'**
  String get missingCoreMessage;

  /// No description provided for @startupTimedOutTitle.
  ///
  /// In en, this message translates to:
  /// **'Core startup timed out'**
  String get startupTimedOutTitle;

  /// No description provided for @startupTimedOutMessage.
  ///
  /// In en, this message translates to:
  /// **'The local core did not complete its secure startup in time. Close GixGiz and try again.'**
  String get startupTimedOutMessage;

  /// No description provided for @connectionLostTitle.
  ///
  /// In en, this message translates to:
  /// **'Core connection lost'**
  String get connectionLostTitle;

  /// No description provided for @connectionLostMessage.
  ///
  /// In en, this message translates to:
  /// **'The authenticated local connection ended unexpectedly. Check again to reconnect.'**
  String get connectionLostMessage;

  /// No description provided for @protocolMismatchTitle.
  ///
  /// In en, this message translates to:
  /// **'Core update required'**
  String get protocolMismatchTitle;

  /// No description provided for @protocolMismatchMessage.
  ///
  /// In en, this message translates to:
  /// **'The desktop and bundled core use incompatible protocol versions. Repair or update GixGiz.'**
  String get protocolMismatchMessage;

  /// No description provided for @authenticationFailedTitle.
  ///
  /// In en, this message translates to:
  /// **'Core authentication failed'**
  String get authenticationFailedTitle;

  /// No description provided for @authenticationFailedMessage.
  ///
  /// In en, this message translates to:
  /// **'The secure local session could not be authenticated. Restart GixGiz to create a new session.'**
  String get authenticationFailedMessage;

  /// No description provided for @degradedTitle.
  ///
  /// In en, this message translates to:
  /// **'Core connection degraded'**
  String get degradedTitle;

  /// No description provided for @degradedMessage.
  ///
  /// In en, this message translates to:
  /// **'The desktop received a limited core status. Check again before continuing.'**
  String get degradedMessage;

  /// No description provided for @failedTitle.
  ///
  /// In en, this message translates to:
  /// **'Foundation check failed'**
  String get failedTitle;

  /// No description provided for @failedMessage.
  ///
  /// In en, this message translates to:
  /// **'GixGiz could not check the local core. Review diagnostics, then try again.'**
  String get failedMessage;

  /// No description provided for @cancelledTitle.
  ///
  /// In en, this message translates to:
  /// **'Foundation check cancelled'**
  String get cancelledTitle;

  /// No description provided for @cancelledMessage.
  ///
  /// In en, this message translates to:
  /// **'The check was cancelled. No system changes were made.'**
  String get cancelledMessage;

  /// No description provided for @checkAgainAction.
  ///
  /// In en, this message translates to:
  /// **'Check again'**
  String get checkAgainAction;

  /// No description provided for @diagnosticsLabel.
  ///
  /// In en, this message translates to:
  /// **'Diagnostics'**
  String get diagnosticsLabel;

  /// No description provided for @diagnosticCodeLabel.
  ///
  /// In en, this message translates to:
  /// **'Diagnostic code: {code}'**
  String diagnosticCodeLabel(String code);

  /// No description provided for @foundationStatusSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'Foundation status: {status}. {detail}'**
  String foundationStatusSemanticLabel(String status, String detail);

  /// No description provided for @loadingProgressSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'Foundation check progress'**
  String get loadingProgressSemanticLabel;

  /// No description provided for @inProgressSemanticValue.
  ///
  /// In en, this message translates to:
  /// **'In progress'**
  String get inProgressSemanticValue;

  /// No description provided for @coreApplicationLabel.
  ///
  /// In en, this message translates to:
  /// **'Application'**
  String get coreApplicationLabel;

  /// No description provided for @coreVersionLabel.
  ///
  /// In en, this message translates to:
  /// **'Core version'**
  String get coreVersionLabel;

  /// No description provided for @protocolVersionLabel.
  ///
  /// In en, this message translates to:
  /// **'Protocol'**
  String get protocolVersionLabel;

  /// No description provided for @readinessLabel.
  ///
  /// In en, this message translates to:
  /// **'Readiness'**
  String get readinessLabel;

  /// No description provided for @unknownValue.
  ///
  /// In en, this message translates to:
  /// **'Unknown'**
  String get unknownValue;

  /// No description provided for @coreDetailsSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'Core details: application {application}, version {version}, protocol {protocol}, readiness {readiness}'**
  String coreDetailsSemanticLabel(
    String application,
    String version,
    String protocol,
    String readiness,
  );

  /// No description provided for @aboutSummary.
  ///
  /// In en, this message translates to:
  /// **'Local-first desktop foundation'**
  String get aboutSummary;

  /// No description provided for @releaseLabel.
  ///
  /// In en, this message translates to:
  /// **'Release'**
  String get releaseLabel;

  /// No description provided for @applicationIdLabel.
  ///
  /// In en, this message translates to:
  /// **'Application ID'**
  String get applicationIdLabel;

  /// No description provided for @coreConnectionLabel.
  ///
  /// In en, this message translates to:
  /// **'Local core'**
  String get coreConnectionLabel;

  /// No description provided for @coreNotConnectedValue.
  ///
  /// In en, this message translates to:
  /// **'Not connected in this build'**
  String get coreNotConnectedValue;

  /// No description provided for @hardwareScanIdleTitle.
  ///
  /// In en, this message translates to:
  /// **'Hardware evidence'**
  String get hardwareScanIdleTitle;

  /// No description provided for @hardwareScanIdleMessage.
  ///
  /// In en, this message translates to:
  /// **'Scan this PC for local OS, processor, physical memory, display adapter, acceleration, and storage evidence.'**
  String get hardwareScanIdleMessage;

  /// No description provided for @hardwareScanLoadingTitle.
  ///
  /// In en, this message translates to:
  /// **'Scanning hardware'**
  String get hardwareScanLoadingTitle;

  /// No description provided for @hardwareScanLoadingMessage.
  ///
  /// In en, this message translates to:
  /// **'GixGiz is collecting bounded, non-elevated Windows evidence.'**
  String get hardwareScanLoadingMessage;

  /// No description provided for @hardwareScanReadyTitle.
  ///
  /// In en, this message translates to:
  /// **'Hardware evidence ready'**
  String get hardwareScanReadyTitle;

  /// No description provided for @hardwareScanReadyMessage.
  ///
  /// In en, this message translates to:
  /// **'All requested evidence was reported reliably.'**
  String get hardwareScanReadyMessage;

  /// No description provided for @hardwareScanPartialTitle.
  ///
  /// In en, this message translates to:
  /// **'Hardware evidence partially available'**
  String get hardwareScanPartialTitle;

  /// No description provided for @hardwareScanPartialMessage.
  ///
  /// In en, this message translates to:
  /// **'The profile is usable, and unavailable values remain explicitly unknown.'**
  String get hardwareScanPartialMessage;

  /// No description provided for @hardwareScanFailedTitle.
  ///
  /// In en, this message translates to:
  /// **'Hardware scan failed'**
  String get hardwareScanFailedTitle;

  /// No description provided for @hardwareScanFailedMessage.
  ///
  /// In en, this message translates to:
  /// **'GixGiz could not produce a usable hardware profile. Review diagnostics, then try again.'**
  String get hardwareScanFailedMessage;

  /// No description provided for @hardwareScanCancelledTitle.
  ///
  /// In en, this message translates to:
  /// **'Hardware scan cancelled'**
  String get hardwareScanCancelledTitle;

  /// No description provided for @hardwareScanCancelledMessage.
  ///
  /// In en, this message translates to:
  /// **'The scan stopped without changing system settings.'**
  String get hardwareScanCancelledMessage;

  /// No description provided for @hardwareScanStartAction.
  ///
  /// In en, this message translates to:
  /// **'Scan hardware'**
  String get hardwareScanStartAction;

  /// No description provided for @hardwareScanAgainAction.
  ///
  /// In en, this message translates to:
  /// **'Scan again'**
  String get hardwareScanAgainAction;

  /// No description provided for @hardwareScanCancelAction.
  ///
  /// In en, this message translates to:
  /// **'Cancel scan'**
  String get hardwareScanCancelAction;

  /// No description provided for @hardwareScanProgressSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'Hardware evidence scan progress'**
  String get hardwareScanProgressSemanticLabel;

  /// No description provided for @hardwareScanStatusSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'Hardware scan status: {status}. {detail}'**
  String hardwareScanStatusSemanticLabel(String status, String detail);

  /// No description provided for @hardwareProfileSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'Hardware profile {completeness}, schema version {version}'**
  String hardwareProfileSemanticLabel(String completeness, int version);

  /// No description provided for @hardwareOperatingSystemLabel.
  ///
  /// In en, this message translates to:
  /// **'Operating system'**
  String get hardwareOperatingSystemLabel;

  /// No description provided for @hardwareCpuLabel.
  ///
  /// In en, this message translates to:
  /// **'Processor'**
  String get hardwareCpuLabel;

  /// No description provided for @hardwarePhysicalMemoryLabel.
  ///
  /// In en, this message translates to:
  /// **'Physical memory'**
  String get hardwarePhysicalMemoryLabel;

  /// No description provided for @hardwareGpuLabel.
  ///
  /// In en, this message translates to:
  /// **'Display adapter'**
  String get hardwareGpuLabel;

  /// No description provided for @hardwareGpuNumberLabel.
  ///
  /// In en, this message translates to:
  /// **'Display adapter {number}'**
  String hardwareGpuNumberLabel(int number);

  /// No description provided for @hardwareAccelerationLabel.
  ///
  /// In en, this message translates to:
  /// **'Acceleration evidence'**
  String get hardwareAccelerationLabel;

  /// No description provided for @hardwareStorageLabel.
  ///
  /// In en, this message translates to:
  /// **'Application storage'**
  String get hardwareStorageLabel;

  /// No description provided for @hardwareOperatingSystemValue.
  ///
  /// In en, this message translates to:
  /// **'{name}, version {version}, {architecture}'**
  String hardwareOperatingSystemValue(
    String name,
    String version,
    String architecture,
  );

  /// No description provided for @hardwareCpuValue.
  ///
  /// In en, this message translates to:
  /// **'{name}, {physical} physical cores, {logical} logical processors'**
  String hardwareCpuValue(String name, String physical, String logical);

  /// No description provided for @hardwareMemoryValue.
  ///
  /// In en, this message translates to:
  /// **'{total} total, {available} available'**
  String hardwareMemoryValue(String total, String available);

  /// No description provided for @hardwareGpuValue.
  ///
  /// In en, this message translates to:
  /// **'{name}, dedicated memory {dedicated}, shared memory {shared}'**
  String hardwareGpuValue(String name, String dedicated, String shared);

  /// No description provided for @hardwareAccelerationValue.
  ///
  /// In en, this message translates to:
  /// **'{kind}: {support}'**
  String hardwareAccelerationValue(String kind, String support);

  /// No description provided for @hardwareStorageValue.
  ///
  /// In en, this message translates to:
  /// **'{capacity} capacity, {free} free, {filesystem}, {media}'**
  String hardwareStorageValue(
    String capacity,
    String free,
    String filesystem,
    String media,
  );

  /// No description provided for @hardwareEvidenceDetail.
  ///
  /// In en, this message translates to:
  /// **'Source: {source}. {reason}'**
  String hardwareEvidenceDetail(String source, String reason);

  /// No description provided for @supportedValue.
  ///
  /// In en, this message translates to:
  /// **'Supported'**
  String get supportedValue;

  /// No description provided for @notSupportedValue.
  ///
  /// In en, this message translates to:
  /// **'Not supported'**
  String get notSupportedValue;

  /// No description provided for @capabilityTitle.
  ///
  /// In en, this message translates to:
  /// **'Plan for this PC'**
  String get capabilityTitle;

  /// No description provided for @capabilityWorkloadLabel.
  ///
  /// In en, this message translates to:
  /// **'Primary use'**
  String get capabilityWorkloadLabel;

  /// No description provided for @capabilityWorkloadGeneral.
  ///
  /// In en, this message translates to:
  /// **'Writing and chat'**
  String get capabilityWorkloadGeneral;

  /// No description provided for @capabilityWorkloadCoding.
  ///
  /// In en, this message translates to:
  /// **'Coding'**
  String get capabilityWorkloadCoding;

  /// No description provided for @capabilityPriorityLabel.
  ///
  /// In en, this message translates to:
  /// **'Preference'**
  String get capabilityPriorityLabel;

  /// No description provided for @capabilityPriorityBalanced.
  ///
  /// In en, this message translates to:
  /// **'Balanced'**
  String get capabilityPriorityBalanced;

  /// No description provided for @capabilityPriorityFastest.
  ///
  /// In en, this message translates to:
  /// **'Fastest setup'**
  String get capabilityPriorityFastest;

  /// No description provided for @capabilityPriorityLightest.
  ///
  /// In en, this message translates to:
  /// **'Lowest resource use'**
  String get capabilityPriorityLightest;

  /// No description provided for @capabilityPriorityQuality.
  ///
  /// In en, this message translates to:
  /// **'Best quality within safe limits'**
  String get capabilityPriorityQuality;

  /// No description provided for @capabilityLargerOptionLabel.
  ///
  /// In en, this message translates to:
  /// **'Show a larger safe option'**
  String get capabilityLargerOptionLabel;

  /// No description provided for @capabilityGenerateAction.
  ///
  /// In en, this message translates to:
  /// **'Generate plan'**
  String get capabilityGenerateAction;

  /// No description provided for @capabilityProgressSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'Capability planning progress'**
  String get capabilityProgressSemanticLabel;

  /// No description provided for @capabilityIdleMessage.
  ///
  /// In en, this message translates to:
  /// **'No plan has been generated for this hardware profile.'**
  String get capabilityIdleMessage;

  /// No description provided for @capabilityIdleSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'Capability plan not generated'**
  String get capabilityIdleSemanticLabel;

  /// No description provided for @capabilityLoadingMessage.
  ///
  /// In en, this message translates to:
  /// **'Checking safe options for this PC.'**
  String get capabilityLoadingMessage;

  /// No description provided for @capabilityLoadingSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'Capability planning in progress'**
  String get capabilityLoadingSemanticLabel;

  /// No description provided for @capabilityReadySemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'Recommended plan: {name}. Confidence: {confidence}.'**
  String capabilityReadySemanticLabel(String name, String confidence);

  /// No description provided for @capabilityRecommendedTitle.
  ///
  /// In en, this message translates to:
  /// **'Recommended'**
  String get capabilityRecommendedTitle;

  /// No description provided for @capabilityFallbackTitle.
  ///
  /// In en, this message translates to:
  /// **'Smaller fallback'**
  String get capabilityFallbackTitle;

  /// No description provided for @capabilityLargerTitle.
  ///
  /// In en, this message translates to:
  /// **'Larger option'**
  String get capabilityLargerTitle;

  /// No description provided for @capabilityMemoryLabel.
  ///
  /// In en, this message translates to:
  /// **'Memory allowance'**
  String get capabilityMemoryLabel;

  /// No description provided for @capabilityStorageEstimateLabel.
  ///
  /// In en, this message translates to:
  /// **'Storage allowance'**
  String get capabilityStorageEstimateLabel;

  /// No description provided for @capabilityModeLabel.
  ///
  /// In en, this message translates to:
  /// **'Operating mode'**
  String get capabilityModeLabel;

  /// No description provided for @capabilityStandardMode.
  ///
  /// In en, this message translates to:
  /// **'Standard'**
  String get capabilityStandardMode;

  /// No description provided for @capabilityAcceleratedMode.
  ///
  /// In en, this message translates to:
  /// **'Accelerated'**
  String get capabilityAcceleratedMode;

  /// No description provided for @capabilityConfidenceLabel.
  ///
  /// In en, this message translates to:
  /// **'Confidence'**
  String get capabilityConfidenceLabel;

  /// No description provided for @capabilityConfidenceHigh.
  ///
  /// In en, this message translates to:
  /// **'High'**
  String get capabilityConfidenceHigh;

  /// No description provided for @capabilityConfidenceMedium.
  ///
  /// In en, this message translates to:
  /// **'Medium'**
  String get capabilityConfidenceMedium;

  /// No description provided for @capabilityConfidenceLow.
  ///
  /// In en, this message translates to:
  /// **'Low'**
  String get capabilityConfidenceLow;

  /// No description provided for @capabilityReasonsLabel.
  ///
  /// In en, this message translates to:
  /// **'Why this result'**
  String get capabilityReasonsLabel;

  /// No description provided for @capabilityWarningsLabel.
  ///
  /// In en, this message translates to:
  /// **'Important considerations'**
  String get capabilityWarningsLabel;

  /// No description provided for @capabilityLicenceLabel.
  ///
  /// In en, this message translates to:
  /// **'Licence: {licence}'**
  String capabilityLicenceLabel(String licence);

  /// No description provided for @capabilitySourceLabel.
  ///
  /// In en, this message translates to:
  /// **'Source: {source}'**
  String capabilitySourceLabel(String source);

  /// No description provided for @capabilityVersionsLabel.
  ///
  /// In en, this message translates to:
  /// **'Catalogue {catalogue}; rules {rules}'**
  String capabilityVersionsLabel(String catalogue, String rules);

  /// No description provided for @capabilityNoPlanTitle.
  ///
  /// In en, this message translates to:
  /// **'No safe plan available'**
  String get capabilityNoPlanTitle;

  /// No description provided for @capabilityNoPlanMessage.
  ///
  /// In en, this message translates to:
  /// **'The current evidence or available resources do not support a safe plan.'**
  String get capabilityNoPlanMessage;

  /// No description provided for @capabilityNoPlanSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'No safe capability plan is available'**
  String get capabilityNoPlanSemanticLabel;

  /// No description provided for @capabilityFailedTitle.
  ///
  /// In en, this message translates to:
  /// **'Planning failed'**
  String get capabilityFailedTitle;

  /// No description provided for @capabilityFailedMessage.
  ///
  /// In en, this message translates to:
  /// **'GixGiz could not generate a plan. Review diagnostics, then try again.'**
  String get capabilityFailedMessage;

  /// No description provided for @capabilityFailedSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'Capability planning failed'**
  String get capabilityFailedSemanticLabel;

  /// No description provided for @runtimeTitle.
  ///
  /// In en, this message translates to:
  /// **'Local runtime'**
  String get runtimeTitle;

  /// No description provided for @runtimeIdleTitle.
  ///
  /// In en, this message translates to:
  /// **'Runtime not checked'**
  String get runtimeIdleTitle;

  /// No description provided for @runtimeIdleMessage.
  ///
  /// In en, this message translates to:
  /// **'Check for a compatible local runtime before continuing.'**
  String get runtimeIdleMessage;

  /// No description provided for @runtimeCheckingTitle.
  ///
  /// In en, this message translates to:
  /// **'Checking runtime'**
  String get runtimeCheckingTitle;

  /// No description provided for @runtimeCheckingMessage.
  ///
  /// In en, this message translates to:
  /// **'GixGiz is checking local runtime evidence without changing the installation.'**
  String get runtimeCheckingMessage;

  /// No description provided for @runtimeNotInstalledTitle.
  ///
  /// In en, this message translates to:
  /// **'Runtime not installed'**
  String get runtimeNotInstalledTitle;

  /// No description provided for @runtimeNotInstalledMessage.
  ///
  /// In en, this message translates to:
  /// **'No compatible local runtime was verified. Installation is not available in this step.'**
  String get runtimeNotInstalledMessage;

  /// No description provided for @runtimeInstalledStoppedTitle.
  ///
  /// In en, this message translates to:
  /// **'Runtime installed but stopped'**
  String get runtimeInstalledStoppedTitle;

  /// No description provided for @runtimeInstalledStoppedMessage.
  ///
  /// In en, this message translates to:
  /// **'A compatible local runtime was found, but it is not ready.'**
  String get runtimeInstalledStoppedMessage;

  /// No description provided for @runtimeStartingTitle.
  ///
  /// In en, this message translates to:
  /// **'Runtime starting'**
  String get runtimeStartingTitle;

  /// No description provided for @runtimeStartingMessage.
  ///
  /// In en, this message translates to:
  /// **'The approved local runtime start is in progress.'**
  String get runtimeStartingMessage;

  /// No description provided for @runtimeReadyTitle.
  ///
  /// In en, this message translates to:
  /// **'Runtime ready'**
  String get runtimeReadyTitle;

  /// No description provided for @runtimeReadyMessage.
  ///
  /// In en, this message translates to:
  /// **'The local endpoint, version, and health checks succeeded.'**
  String get runtimeReadyMessage;

  /// No description provided for @runtimeDegradedTitle.
  ///
  /// In en, this message translates to:
  /// **'Runtime needs attention'**
  String get runtimeDegradedTitle;

  /// No description provided for @runtimeDegradedMessage.
  ///
  /// In en, this message translates to:
  /// **'The runtime responded, but some health or capability evidence is limited.'**
  String get runtimeDegradedMessage;

  /// No description provided for @runtimeIncompatibleTitle.
  ///
  /// In en, this message translates to:
  /// **'Runtime version incompatible'**
  String get runtimeIncompatibleTitle;

  /// No description provided for @runtimeIncompatibleMessage.
  ///
  /// In en, this message translates to:
  /// **'The detected runtime version is not supported by this GixGiz release.'**
  String get runtimeIncompatibleMessage;

  /// No description provided for @runtimeUpdatingTitle.
  ///
  /// In en, this message translates to:
  /// **'Runtime updating'**
  String get runtimeUpdatingTitle;

  /// No description provided for @runtimeUpdatingMessage.
  ///
  /// In en, this message translates to:
  /// **'An external update is in progress. GixGiz will not change it automatically.'**
  String get runtimeUpdatingMessage;

  /// No description provided for @runtimeFailedTitle.
  ///
  /// In en, this message translates to:
  /// **'Runtime check failed'**
  String get runtimeFailedTitle;

  /// No description provided for @runtimeFailedMessage.
  ///
  /// In en, this message translates to:
  /// **'GixGiz could not obtain a safe runtime status. Review diagnostics, then try again.'**
  String get runtimeFailedMessage;

  /// No description provided for @runtimeUnknownTitle.
  ///
  /// In en, this message translates to:
  /// **'Runtime status unknown'**
  String get runtimeUnknownTitle;

  /// No description provided for @runtimeUnknownMessage.
  ///
  /// In en, this message translates to:
  /// **'The runtime reported a state this desktop does not recognize. Update GixGiz before continuing.'**
  String get runtimeUnknownMessage;

  /// No description provided for @runtimeOperationTitle.
  ///
  /// In en, this message translates to:
  /// **'Runtime operation in progress'**
  String get runtimeOperationTitle;

  /// No description provided for @runtimeOperationMessage.
  ///
  /// In en, this message translates to:
  /// **'GixGiz is waiting for the approved operation to reach a verified terminal state.'**
  String get runtimeOperationMessage;

  /// No description provided for @runtimeOperationFailedTitle.
  ///
  /// In en, this message translates to:
  /// **'Runtime {operation} failed'**
  String runtimeOperationFailedTitle(String operation);

  /// No description provided for @runtimeOperationFailedMessage.
  ///
  /// In en, this message translates to:
  /// **'GixGiz could not complete the approved {operation} operation. Review diagnostics and the recommended action.'**
  String runtimeOperationFailedMessage(String operation);

  /// No description provided for @runtimeOperationKindStart.
  ///
  /// In en, this message translates to:
  /// **'start'**
  String get runtimeOperationKindStart;

  /// No description provided for @runtimeOperationKindStop.
  ///
  /// In en, this message translates to:
  /// **'stop'**
  String get runtimeOperationKindStop;

  /// No description provided for @runtimeOperationKindRestart.
  ///
  /// In en, this message translates to:
  /// **'restart'**
  String get runtimeOperationKindRestart;

  /// No description provided for @runtimeOperationKindUnknown.
  ///
  /// In en, this message translates to:
  /// **'lifecycle operation'**
  String get runtimeOperationKindUnknown;

  /// No description provided for @runtimeCancelledTitle.
  ///
  /// In en, this message translates to:
  /// **'Runtime operation cancelled'**
  String get runtimeCancelledTitle;

  /// No description provided for @runtimeCancelledMessage.
  ///
  /// In en, this message translates to:
  /// **'The operation was cancelled. Check the current runtime status before continuing.'**
  String get runtimeCancelledMessage;

  /// No description provided for @runtimeProviderLabel.
  ///
  /// In en, this message translates to:
  /// **'Runtime'**
  String get runtimeProviderLabel;

  /// No description provided for @runtimeVersionLabel.
  ///
  /// In en, this message translates to:
  /// **'Version'**
  String get runtimeVersionLabel;

  /// No description provided for @runtimeOwnershipLabel.
  ///
  /// In en, this message translates to:
  /// **'Ownership'**
  String get runtimeOwnershipLabel;

  /// No description provided for @runtimeReuseConsentLabel.
  ///
  /// In en, this message translates to:
  /// **'Reuse permission'**
  String get runtimeReuseConsentLabel;

  /// No description provided for @runtimeManagementConsentLabel.
  ///
  /// In en, this message translates to:
  /// **'Management permission'**
  String get runtimeManagementConsentLabel;

  /// No description provided for @runtimeEndpointLabel.
  ///
  /// In en, this message translates to:
  /// **'Local endpoint'**
  String get runtimeEndpointLabel;

  /// No description provided for @runtimeOwnershipExternal.
  ///
  /// In en, this message translates to:
  /// **'Installed outside GixGiz'**
  String get runtimeOwnershipExternal;

  /// No description provided for @runtimeOwnershipManaged.
  ///
  /// In en, this message translates to:
  /// **'Managed by GixGiz'**
  String get runtimeOwnershipManaged;

  /// No description provided for @runtimeOwnershipBundled.
  ///
  /// In en, this message translates to:
  /// **'Included with GixGiz'**
  String get runtimeOwnershipBundled;

  /// No description provided for @runtimeOwnershipUnknown.
  ///
  /// In en, this message translates to:
  /// **'Ownership not verified'**
  String get runtimeOwnershipUnknown;

  /// No description provided for @runtimeConsentNotRequested.
  ///
  /// In en, this message translates to:
  /// **'Reuse permission not granted'**
  String get runtimeConsentNotRequested;

  /// No description provided for @runtimeConsentReuseApproved.
  ///
  /// In en, this message translates to:
  /// **'Approved for reuse only'**
  String get runtimeConsentReuseApproved;

  /// No description provided for @runtimeConsentManagementApproved.
  ///
  /// In en, this message translates to:
  /// **'Approved for management'**
  String get runtimeConsentManagementApproved;

  /// No description provided for @runtimeConsentDenied.
  ///
  /// In en, this message translates to:
  /// **'Reuse declined'**
  String get runtimeConsentDenied;

  /// No description provided for @runtimeConsentUnknown.
  ///
  /// In en, this message translates to:
  /// **'Permission state unknown'**
  String get runtimeConsentUnknown;

  /// No description provided for @runtimeManagementConsentNotRequested.
  ///
  /// In en, this message translates to:
  /// **'Management permission not granted'**
  String get runtimeManagementConsentNotRequested;

  /// No description provided for @runtimeManagementConsentApproved.
  ///
  /// In en, this message translates to:
  /// **'Approved for management'**
  String get runtimeManagementConsentApproved;

  /// No description provided for @runtimeManagementConsentDenied.
  ///
  /// In en, this message translates to:
  /// **'Management declined'**
  String get runtimeManagementConsentDenied;

  /// No description provided for @runtimeManagementConsentUnknown.
  ///
  /// In en, this message translates to:
  /// **'Management permission unknown'**
  String get runtimeManagementConsentUnknown;

  /// No description provided for @runtimeEndpointVerified.
  ///
  /// In en, this message translates to:
  /// **'Verified local endpoint'**
  String get runtimeEndpointVerified;

  /// No description provided for @runtimeEndpointRejected.
  ///
  /// In en, this message translates to:
  /// **'Endpoint rejected'**
  String get runtimeEndpointRejected;

  /// No description provided for @runtimeEndpointUnknown.
  ///
  /// In en, this message translates to:
  /// **'Endpoint not verified'**
  String get runtimeEndpointUnknown;

  /// No description provided for @runtimeExternalNotice.
  ///
  /// In en, this message translates to:
  /// **'This installation remains externally owned. Reuse does not let GixGiz update, uninstall, reconfigure, or claim it.'**
  String get runtimeExternalNotice;

  /// No description provided for @runtimeManagementRequiredNotice.
  ///
  /// In en, this message translates to:
  /// **'Start, stop, and restart remain unavailable because management permission is separate from reuse.'**
  String get runtimeManagementRequiredNotice;

  /// No description provided for @runtimeExternalManagementRequiredNotice.
  ///
  /// In en, this message translates to:
  /// **'Start, stop, and restart remain unavailable because management permission is separate from reuse. Manage this external installation with its existing controls.'**
  String get runtimeExternalManagementRequiredNotice;

  /// No description provided for @runtimeConsentPromptTitle.
  ///
  /// In en, this message translates to:
  /// **'Allow runtime reuse?'**
  String get runtimeConsentPromptTitle;

  /// No description provided for @runtimeConsentPromptMessage.
  ///
  /// In en, this message translates to:
  /// **'Allowing reuse lets GixGiz check this local runtime and list its installed models when current health and compatibility evidence permits. Ownership stays external, and this does not approve updates, uninstallation, reconfiguration, or other system changes.'**
  String get runtimeConsentPromptMessage;

  /// No description provided for @runtimeConsentApproveAction.
  ///
  /// In en, this message translates to:
  /// **'Allow reuse'**
  String get runtimeConsentApproveAction;

  /// No description provided for @runtimeConsentCancelAction.
  ///
  /// In en, this message translates to:
  /// **'Not now'**
  String get runtimeConsentCancelAction;

  /// No description provided for @runtimeRefreshAction.
  ///
  /// In en, this message translates to:
  /// **'Check runtime'**
  String get runtimeRefreshAction;

  /// No description provided for @runtimeStartAction.
  ///
  /// In en, this message translates to:
  /// **'Start runtime'**
  String get runtimeStartAction;

  /// No description provided for @runtimeStopAction.
  ///
  /// In en, this message translates to:
  /// **'Stop runtime'**
  String get runtimeStopAction;

  /// No description provided for @runtimeRestartAction.
  ///
  /// In en, this message translates to:
  /// **'Restart runtime'**
  String get runtimeRestartAction;

  /// No description provided for @runtimeCancelAction.
  ///
  /// In en, this message translates to:
  /// **'Cancel operation'**
  String get runtimeCancelAction;

  /// No description provided for @runtimeModelsAction.
  ///
  /// In en, this message translates to:
  /// **'Show installed models'**
  String get runtimeModelsAction;

  /// No description provided for @runtimeModelsHideAction.
  ///
  /// In en, this message translates to:
  /// **'Hide installed models'**
  String get runtimeModelsHideAction;

  /// No description provided for @runtimeModelsTitle.
  ///
  /// In en, this message translates to:
  /// **'Installed models'**
  String get runtimeModelsTitle;

  /// No description provided for @runtimeModelsProgressSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'Installed model inventory progress'**
  String get runtimeModelsProgressSemanticLabel;

  /// No description provided for @runtimeModelsEmpty.
  ///
  /// In en, this message translates to:
  /// **'No installed models were reported.'**
  String get runtimeModelsEmpty;

  /// No description provided for @runtimeModelsFailedMessage.
  ///
  /// In en, this message translates to:
  /// **'GixGiz could not list installed models. Review diagnostics, then try again.'**
  String get runtimeModelsFailedMessage;

  /// No description provided for @runtimeModelsTruncated.
  ///
  /// In en, this message translates to:
  /// **'More installed models exist than can be shown safely.'**
  String get runtimeModelsTruncated;

  /// No description provided for @runtimeExternalModelLabel.
  ///
  /// In en, this message translates to:
  /// **'External model'**
  String get runtimeExternalModelLabel;

  /// No description provided for @runtimeModelSizeLabel.
  ///
  /// In en, this message translates to:
  /// **'Size: {size}'**
  String runtimeModelSizeLabel(String size);

  /// No description provided for @runtimeModelCatalogueLabel.
  ///
  /// In en, this message translates to:
  /// **'Catalogue model: {model}'**
  String runtimeModelCatalogueLabel(String model);

  /// No description provided for @runtimeReasonsLabel.
  ///
  /// In en, this message translates to:
  /// **'Status details'**
  String get runtimeReasonsLabel;

  /// No description provided for @runtimeWarningsLabel.
  ///
  /// In en, this message translates to:
  /// **'Important considerations'**
  String get runtimeWarningsLabel;

  /// No description provided for @runtimeReasonInstallationNotFound.
  ///
  /// In en, this message translates to:
  /// **'No supported local runtime installation was found.'**
  String get runtimeReasonInstallationNotFound;

  /// No description provided for @runtimeReasonExecutableVerified.
  ///
  /// In en, this message translates to:
  /// **'The runtime executable location was verified.'**
  String get runtimeReasonExecutableVerified;

  /// No description provided for @runtimeReasonEndpointUnavailable.
  ///
  /// In en, this message translates to:
  /// **'The local runtime endpoint did not respond.'**
  String get runtimeReasonEndpointUnavailable;

  /// No description provided for @runtimeReasonEndpointReachable.
  ///
  /// In en, this message translates to:
  /// **'The local runtime endpoint responded.'**
  String get runtimeReasonEndpointReachable;

  /// No description provided for @runtimeReasonEndpointUnsafe.
  ///
  /// In en, this message translates to:
  /// **'The runtime endpoint was rejected because it was not safely local.'**
  String get runtimeReasonEndpointUnsafe;

  /// No description provided for @runtimeReasonVersionCompatible.
  ///
  /// In en, this message translates to:
  /// **'The reported runtime version is compatible.'**
  String get runtimeReasonVersionCompatible;

  /// No description provided for @runtimeReasonVersionIncompatible.
  ///
  /// In en, this message translates to:
  /// **'The reported runtime version is incompatible.'**
  String get runtimeReasonVersionIncompatible;

  /// No description provided for @runtimeReasonVersionUnverified.
  ///
  /// In en, this message translates to:
  /// **'The runtime version could not be verified.'**
  String get runtimeReasonVersionUnverified;

  /// No description provided for @runtimeReasonEvidenceIncomplete.
  ///
  /// In en, this message translates to:
  /// **'Some runtime health evidence is incomplete.'**
  String get runtimeReasonEvidenceIncomplete;

  /// No description provided for @runtimeReasonOwnershipRequired.
  ///
  /// In en, this message translates to:
  /// **'GixGiz ownership is required for this operation.'**
  String get runtimeReasonOwnershipRequired;

  /// No description provided for @runtimeReasonConsentRequired.
  ///
  /// In en, this message translates to:
  /// **'Explicit permission is required for this capability.'**
  String get runtimeReasonConsentRequired;

  /// No description provided for @runtimeReasonOperationUnsupported.
  ///
  /// In en, this message translates to:
  /// **'This runtime operation is not supported.'**
  String get runtimeReasonOperationUnsupported;

  /// No description provided for @runtimeReasonProcessExited.
  ///
  /// In en, this message translates to:
  /// **'The managed runtime process exited before it became ready.'**
  String get runtimeReasonProcessExited;

  /// No description provided for @runtimeReasonUnknown.
  ///
  /// In en, this message translates to:
  /// **'Additional runtime evidence is not recognized by this GixGiz version.'**
  String get runtimeReasonUnknown;

  /// No description provided for @runtimeWarningExternalInstallation.
  ///
  /// In en, this message translates to:
  /// **'This runtime is installed and managed outside GixGiz.'**
  String get runtimeWarningExternalInstallation;

  /// No description provided for @runtimeWarningEndpointExposure.
  ///
  /// In en, this message translates to:
  /// **'The runtime endpoint may be exposed beyond this device.'**
  String get runtimeWarningEndpointExposure;

  /// No description provided for @runtimeWarningVersionUntested.
  ///
  /// In en, this message translates to:
  /// **'This runtime version has not been verified with this GixGiz release.'**
  String get runtimeWarningVersionUntested;

  /// No description provided for @runtimeWarningPartialEvidence.
  ///
  /// In en, this message translates to:
  /// **'Only partial runtime evidence is available.'**
  String get runtimeWarningPartialEvidence;

  /// No description provided for @runtimeWarningModelInventoryTruncated.
  ///
  /// In en, this message translates to:
  /// **'The installed model list was limited for safe display.'**
  String get runtimeWarningModelInventoryTruncated;

  /// No description provided for @runtimeWarningUnknown.
  ///
  /// In en, this message translates to:
  /// **'An unrecognized runtime warning was reported.'**
  String get runtimeWarningUnknown;

  /// No description provided for @runtimeRecommendedAction.
  ///
  /// In en, this message translates to:
  /// **'Recommended action: {action}'**
  String runtimeRecommendedAction(String action);

  /// No description provided for @runtimeRecoveryRetry.
  ///
  /// In en, this message translates to:
  /// **'Try the operation again.'**
  String get runtimeRecoveryRetry;

  /// No description provided for @runtimeRecoveryRestart.
  ///
  /// In en, this message translates to:
  /// **'Restart GixGiz, then check the runtime again.'**
  String get runtimeRecoveryRestart;

  /// No description provided for @runtimeRecoveryCheckPrerequisites.
  ///
  /// In en, this message translates to:
  /// **'Check the runtime prerequisites, then try again.'**
  String get runtimeRecoveryCheckPrerequisites;

  /// No description provided for @runtimeRecoveryContactSupport.
  ///
  /// In en, this message translates to:
  /// **'Contact support with the diagnostic code.'**
  String get runtimeRecoveryContactSupport;

  /// No description provided for @runtimeRecoveryNoAction.
  ///
  /// In en, this message translates to:
  /// **'No action is required.'**
  String get runtimeRecoveryNoAction;

  /// No description provided for @runtimeRecoveryUnknown.
  ///
  /// In en, this message translates to:
  /// **'Review diagnostics before trying again.'**
  String get runtimeRecoveryUnknown;

  /// No description provided for @runtimeProgressSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'Runtime operation progress'**
  String get runtimeProgressSemanticLabel;

  /// No description provided for @runtimeStatusSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'Runtime status: {status}. {message} Ownership: {ownership}. Permission: {consent}.'**
  String runtimeStatusSemanticLabel(
    String status,
    String message,
    String ownership,
    String consent,
  );

  /// No description provided for @runtimeDetailsSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'Runtime details: {provider}, version {version}, endpoint {endpoint}, ownership {ownership}, reuse permission {reuseConsent}, management permission {managementConsent}.'**
  String runtimeDetailsSemanticLabel(
    String provider,
    String version,
    String endpoint,
    String ownership,
    String reuseConsent,
    String managementConsent,
  );
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(lookupAppLocalizations(locale));
  }

  @override
  bool isSupported(Locale locale) =>
      <String>['en'].contains(locale.languageCode);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

AppLocalizations lookupAppLocalizations(Locale locale) {
  // Lookup logic when only language code is specified.
  switch (locale.languageCode) {
    case 'en':
      return AppLocalizationsEn();
  }

  throw FlutterError(
    'AppLocalizations.delegate failed to load unsupported locale "$locale". This is likely '
    'an issue with the localizations generation tool. Please file an issue '
    'on GitHub with a reproducible sample app and the gen-l10n configuration '
    'that was used.',
  );
}
