// Generated by Flutter gen-l10n. Do not edit.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'GixGiz';

  @override
  String get appMarkSemanticLabel => 'GixGiz application mark';

  @override
  String get foundationNavigationLabel => 'Foundation';

  @override
  String get aboutNavigationLabel => 'About';

  @override
  String get foundationTitle => 'Foundation';

  @override
  String get aboutTitle => 'About GixGiz';

  @override
  String get loadingTitle => 'Checking foundation';

  @override
  String get loadingMessage =>
      'GixGiz is checking whether the local core is available.';

  @override
  String get coreReadyTitle => 'Platform core ready';

  @override
  String get coreReadyMessage =>
      'The authenticated Rust platform core is available.';

  @override
  String get notConnectedTitle => 'Core not connected';

  @override
  String get notConnectedMessage =>
      'The local platform core is unavailable. Check again before continuing.';

  @override
  String get missingCoreTitle => 'Core component missing';

  @override
  String get missingCoreMessage =>
      'The bundled Rust core could not be found. Repair or reinstall GixGiz, then try again.';

  @override
  String get startupTimedOutTitle => 'Core startup timed out';

  @override
  String get startupTimedOutMessage =>
      'The local core did not complete its secure startup in time. Close GixGiz and try again.';

  @override
  String get connectionLostTitle => 'Core connection lost';

  @override
  String get connectionLostMessage =>
      'The authenticated local connection ended unexpectedly. Check again to reconnect.';

  @override
  String get protocolMismatchTitle => 'Core update required';

  @override
  String get protocolMismatchMessage =>
      'The desktop and bundled core use incompatible protocol versions. Repair or update GixGiz.';

  @override
  String get authenticationFailedTitle => 'Core authentication failed';

  @override
  String get authenticationFailedMessage =>
      'The secure local session could not be authenticated. Restart GixGiz to create a new session.';

  @override
  String get degradedTitle => 'Core connection degraded';

  @override
  String get degradedMessage =>
      'The desktop received a limited core status. Check again before continuing.';

  @override
  String get failedTitle => 'Foundation check failed';

  @override
  String get failedMessage =>
      'GixGiz could not check the local core. Review diagnostics, then try again.';

  @override
  String get cancelledTitle => 'Foundation check cancelled';

  @override
  String get cancelledMessage =>
      'The check was cancelled. No system changes were made.';

  @override
  String get checkAgainAction => 'Check again';

  @override
  String get diagnosticsLabel => 'Diagnostics';

  @override
  String diagnosticCodeLabel(String code) {
    return 'Diagnostic code: $code';
  }

  @override
  String foundationStatusSemanticLabel(String status, String detail) {
    return 'Foundation status: $status. $detail';
  }

  @override
  String get loadingProgressSemanticLabel => 'Foundation check progress';

  @override
  String get inProgressSemanticValue => 'In progress';

  @override
  String get coreApplicationLabel => 'Application';

  @override
  String get coreVersionLabel => 'Core version';

  @override
  String get protocolVersionLabel => 'Protocol';

  @override
  String get readinessLabel => 'Readiness';

  @override
  String get unknownValue => 'Unknown';

  @override
  String coreDetailsSemanticLabel(
    String application,
    String version,
    String protocol,
    String readiness,
  ) {
    return 'Core details: application $application, version $version, protocol $protocol, readiness $readiness';
  }

  @override
  String get aboutSummary => 'Local-first desktop foundation';

  @override
  String get releaseLabel => 'Release';

  @override
  String get applicationIdLabel => 'Application ID';

  @override
  String get coreConnectionLabel => 'Local core';

  @override
  String get coreNotConnectedValue => 'Not connected in this build';

  @override
  String get hardwareScanIdleTitle => 'Hardware evidence';

  @override
  String get hardwareScanIdleMessage =>
      'Scan this PC for local OS, processor, physical memory, display adapter, acceleration, and storage evidence.';

  @override
  String get hardwareScanLoadingTitle => 'Scanning hardware';

  @override
  String get hardwareScanLoadingMessage =>
      'GixGiz is collecting bounded, non-elevated Windows evidence.';

  @override
  String get hardwareScanReadyTitle => 'Hardware evidence ready';

  @override
  String get hardwareScanReadyMessage =>
      'All requested evidence was reported reliably.';

  @override
  String get hardwareScanPartialTitle =>
      'Hardware evidence partially available';

  @override
  String get hardwareScanPartialMessage =>
      'The profile is usable, and unavailable values remain explicitly unknown.';

  @override
  String get hardwareScanFailedTitle => 'Hardware scan failed';

  @override
  String get hardwareScanFailedMessage =>
      'GixGiz could not produce a usable hardware profile. Review diagnostics, then try again.';

  @override
  String get hardwareScanCancelledTitle => 'Hardware scan cancelled';

  @override
  String get hardwareScanCancelledMessage =>
      'The scan stopped without changing system settings.';

  @override
  String get hardwareScanStartAction => 'Scan hardware';

  @override
  String get hardwareScanAgainAction => 'Scan again';

  @override
  String get hardwareScanCancelAction => 'Cancel scan';

  @override
  String get hardwareScanProgressSemanticLabel =>
      'Hardware evidence scan progress';

  @override
  String hardwareScanStatusSemanticLabel(String status, String detail) {
    return 'Hardware scan status: $status. $detail';
  }

  @override
  String hardwareProfileSemanticLabel(String completeness, int version) {
    return 'Hardware profile $completeness, schema version $version';
  }

  @override
  String get hardwareOperatingSystemLabel => 'Operating system';

  @override
  String get hardwareCpuLabel => 'Processor';

  @override
  String get hardwarePhysicalMemoryLabel => 'Physical memory';

  @override
  String get hardwareGpuLabel => 'Display adapter';

  @override
  String hardwareGpuNumberLabel(int number) {
    return 'Display adapter $number';
  }

  @override
  String get hardwareAccelerationLabel => 'Acceleration evidence';

  @override
  String get hardwareStorageLabel => 'Application storage';

  @override
  String hardwareOperatingSystemValue(
    String name,
    String version,
    String architecture,
  ) {
    return '$name, version $version, $architecture';
  }

  @override
  String hardwareCpuValue(String name, String physical, String logical) {
    return '$name, $physical physical cores, $logical logical processors';
  }

  @override
  String hardwareMemoryValue(String total, String available) {
    return '$total total, $available available';
  }

  @override
  String hardwareGpuValue(String name, String dedicated, String shared) {
    return '$name, dedicated memory $dedicated, shared memory $shared';
  }

  @override
  String hardwareAccelerationValue(String kind, String support) {
    return '$kind: $support';
  }

  @override
  String hardwareStorageValue(
    String capacity,
    String free,
    String filesystem,
    String media,
  ) {
    return '$capacity capacity, $free free, $filesystem, $media';
  }

  @override
  String hardwareEvidenceDetail(String source, String reason) {
    return 'Source: $source. $reason';
  }

  @override
  String get supportedValue => 'Supported';

  @override
  String get notSupportedValue => 'Not supported';

  @override
  String get capabilityTitle => 'Plan for this PC';

  @override
  String get capabilityWorkloadLabel => 'Primary use';

  @override
  String get capabilityWorkloadGeneral => 'Writing and chat';

  @override
  String get capabilityWorkloadCoding => 'Coding';

  @override
  String get capabilityPriorityLabel => 'Preference';

  @override
  String get capabilityPriorityBalanced => 'Balanced';

  @override
  String get capabilityPriorityFastest => 'Fastest setup';

  @override
  String get capabilityPriorityLightest => 'Lowest resource use';

  @override
  String get capabilityPriorityQuality => 'Best quality within safe limits';

  @override
  String get capabilityLargerOptionLabel => 'Show a larger safe option';

  @override
  String get capabilityGenerateAction => 'Generate plan';

  @override
  String get capabilityProgressSemanticLabel => 'Capability planning progress';

  @override
  String get capabilityIdleMessage =>
      'No plan has been generated for this hardware profile.';

  @override
  String get capabilityIdleSemanticLabel => 'Capability plan not generated';

  @override
  String get capabilityLoadingMessage => 'Checking safe options for this PC.';

  @override
  String get capabilityLoadingSemanticLabel =>
      'Capability planning in progress';

  @override
  String capabilityReadySemanticLabel(String name, String confidence) {
    return 'Recommended plan: $name. Confidence: $confidence.';
  }

  @override
  String get capabilityRecommendedTitle => 'Recommended';

  @override
  String get capabilityFallbackTitle => 'Smaller fallback';

  @override
  String get capabilityLargerTitle => 'Larger option';

  @override
  String get capabilityMemoryLabel => 'Memory allowance';

  @override
  String get capabilityStorageEstimateLabel => 'Storage allowance';

  @override
  String get capabilityModeLabel => 'Operating mode';

  @override
  String get capabilityStandardMode => 'Standard';

  @override
  String get capabilityAcceleratedMode => 'Accelerated';

  @override
  String get capabilityConfidenceLabel => 'Confidence';

  @override
  String get capabilityConfidenceHigh => 'High';

  @override
  String get capabilityConfidenceMedium => 'Medium';

  @override
  String get capabilityConfidenceLow => 'Low';

  @override
  String get capabilityReasonsLabel => 'Why this result';

  @override
  String get capabilityWarningsLabel => 'Important considerations';

  @override
  String capabilityLicenceLabel(String licence) {
    return 'Licence: $licence';
  }

  @override
  String capabilitySourceLabel(String source) {
    return 'Source: $source';
  }

  @override
  String capabilityVersionsLabel(String catalogue, String rules) {
    return 'Catalogue $catalogue; rules $rules';
  }

  @override
  String get capabilityNoPlanTitle => 'No safe plan available';

  @override
  String get capabilityNoPlanMessage =>
      'The current evidence or available resources do not support a safe plan.';

  @override
  String get capabilityNoPlanSemanticLabel =>
      'No safe capability plan is available';

  @override
  String get capabilityFailedTitle => 'Planning failed';

  @override
  String get capabilityFailedMessage =>
      'GixGiz could not generate a plan. Review diagnostics, then try again.';

  @override
  String get capabilityFailedSemanticLabel => 'Capability planning failed';

  @override
  String get runtimeTitle => 'Local runtime';

  @override
  String get runtimeIdleTitle => 'Runtime not checked';

  @override
  String get runtimeIdleMessage =>
      'Check for a compatible local runtime before continuing.';

  @override
  String get runtimeCheckingTitle => 'Checking runtime';

  @override
  String get runtimeCheckingMessage =>
      'GixGiz is checking local runtime evidence without changing the installation.';

  @override
  String get runtimeNotInstalledTitle => 'Runtime not installed';

  @override
  String get runtimeNotInstalledMessage =>
      'No compatible local runtime was verified. Installation is not available in this step.';

  @override
  String get runtimeInstalledStoppedTitle => 'Runtime installed but stopped';

  @override
  String get runtimeInstalledStoppedMessage =>
      'A compatible local runtime was found, but it is not ready.';

  @override
  String get runtimeStartingTitle => 'Runtime starting';

  @override
  String get runtimeStartingMessage =>
      'The approved local runtime start is in progress.';

  @override
  String get runtimeReadyTitle => 'Runtime ready';

  @override
  String get runtimeReadyMessage =>
      'The local endpoint, version, and health checks succeeded.';

  @override
  String get runtimeDegradedTitle => 'Runtime needs attention';

  @override
  String get runtimeDegradedMessage =>
      'The runtime responded, but some health or capability evidence is limited.';

  @override
  String get runtimeIncompatibleTitle => 'Runtime version incompatible';

  @override
  String get runtimeIncompatibleMessage =>
      'The detected runtime version is not supported by this GixGiz release.';

  @override
  String get runtimeUpdatingTitle => 'Runtime updating';

  @override
  String get runtimeUpdatingMessage =>
      'An external update is in progress. GixGiz will not change it automatically.';

  @override
  String get runtimeFailedTitle => 'Runtime check failed';

  @override
  String get runtimeFailedMessage =>
      'GixGiz could not obtain a safe runtime status. Review diagnostics, then try again.';

  @override
  String get runtimeUnknownTitle => 'Runtime status unknown';

  @override
  String get runtimeUnknownMessage =>
      'The runtime reported a state this desktop does not recognize. Update GixGiz before continuing.';

  @override
  String get runtimeOperationTitle => 'Runtime operation in progress';

  @override
  String get runtimeOperationMessage =>
      'GixGiz is waiting for the approved operation to reach a verified terminal state.';

  @override
  String runtimeOperationFailedTitle(String operation) {
    return 'Runtime $operation failed';
  }

  @override
  String runtimeOperationFailedMessage(String operation) {
    return 'GixGiz could not complete the approved $operation operation. Review diagnostics and the recommended action.';
  }

  @override
  String get runtimeOperationKindStart => 'start';

  @override
  String get runtimeOperationKindStop => 'stop';

  @override
  String get runtimeOperationKindRestart => 'restart';

  @override
  String get runtimeOperationKindUnknown => 'lifecycle operation';

  @override
  String get runtimeCancelledTitle => 'Runtime operation cancelled';

  @override
  String get runtimeCancelledMessage =>
      'The operation was cancelled. Check the current runtime status before continuing.';

  @override
  String get runtimeProviderLabel => 'Runtime';

  @override
  String get runtimeVersionLabel => 'Version';

  @override
  String get runtimeOwnershipLabel => 'Ownership';

  @override
  String get runtimeReuseConsentLabel => 'Reuse permission';

  @override
  String get runtimeManagementConsentLabel => 'Management permission';

  @override
  String get runtimeEndpointLabel => 'Local endpoint';

  @override
  String get runtimeOwnershipExternal => 'Installed outside GixGiz';

  @override
  String get runtimeOwnershipManaged => 'Managed by GixGiz';

  @override
  String get runtimeOwnershipBundled => 'Included with GixGiz';

  @override
  String get runtimeOwnershipUnknown => 'Ownership not verified';

  @override
  String get runtimeConsentNotRequested => 'Reuse permission not granted';

  @override
  String get runtimeConsentReuseApproved => 'Approved for reuse only';

  @override
  String get runtimeConsentManagementApproved => 'Approved for management';

  @override
  String get runtimeConsentDenied => 'Reuse declined';

  @override
  String get runtimeConsentUnknown => 'Permission state unknown';

  @override
  String get runtimeManagementConsentNotRequested =>
      'Management permission not granted';

  @override
  String get runtimeManagementConsentApproved => 'Approved for management';

  @override
  String get runtimeManagementConsentDenied => 'Management declined';

  @override
  String get runtimeManagementConsentUnknown => 'Management permission unknown';

  @override
  String get runtimeEndpointVerified => 'Verified local endpoint';

  @override
  String get runtimeEndpointRejected => 'Endpoint rejected';

  @override
  String get runtimeEndpointUnknown => 'Endpoint not verified';

  @override
  String get runtimeExternalNotice =>
      'This installation remains externally owned. Reuse does not let GixGiz update, uninstall, reconfigure, or claim it.';

  @override
  String get runtimeManagementRequiredNotice =>
      'Start, stop, and restart remain unavailable because management permission is separate from reuse.';

  @override
  String get runtimeExternalManagementRequiredNotice =>
      'Start, stop, and restart remain unavailable because management permission is separate from reuse. Manage this external installation with its existing controls.';

  @override
  String get runtimeConsentPromptTitle => 'Allow runtime reuse?';

  @override
  String get runtimeConsentPromptMessage =>
      'Allowing reuse lets GixGiz check this local runtime and list its installed models when current health and compatibility evidence permits. Ownership stays external, and this does not approve updates, uninstallation, reconfiguration, or other system changes.';

  @override
  String get runtimeConsentApproveAction => 'Allow reuse';

  @override
  String get runtimeConsentCancelAction => 'Not now';

  @override
  String get runtimeRefreshAction => 'Check runtime';

  @override
  String get runtimeStartAction => 'Start runtime';

  @override
  String get runtimeStopAction => 'Stop runtime';

  @override
  String get runtimeRestartAction => 'Restart runtime';

  @override
  String get runtimeCancelAction => 'Cancel operation';

  @override
  String get runtimeModelsAction => 'Show installed models';

  @override
  String get runtimeModelsHideAction => 'Hide installed models';

  @override
  String get runtimeModelsTitle => 'Installed models';

  @override
  String get runtimeModelsProgressSemanticLabel =>
      'Installed model inventory progress';

  @override
  String get runtimeModelsEmpty => 'No installed models were reported.';

  @override
  String get runtimeModelsFailedMessage =>
      'GixGiz could not list installed models. Review diagnostics, then try again.';

  @override
  String get runtimeModelsTruncated =>
      'More installed models exist than can be shown safely.';

  @override
  String get runtimeExternalModelLabel => 'External model';

  @override
  String runtimeModelSizeLabel(String size) {
    return 'Size: $size';
  }

  @override
  String runtimeModelCatalogueLabel(String model) {
    return 'Catalogue model: $model';
  }

  @override
  String get runtimeReasonsLabel => 'Status details';

  @override
  String get runtimeWarningsLabel => 'Important considerations';

  @override
  String get runtimeReasonInstallationNotFound =>
      'No supported local runtime installation was found.';

  @override
  String get runtimeReasonExecutableVerified =>
      'The runtime executable location was verified.';

  @override
  String get runtimeReasonEndpointUnavailable =>
      'The local runtime endpoint did not respond.';

  @override
  String get runtimeReasonEndpointReachable =>
      'The local runtime endpoint responded.';

  @override
  String get runtimeReasonEndpointUnsafe =>
      'The runtime endpoint was rejected because it was not safely local.';

  @override
  String get runtimeReasonVersionCompatible =>
      'The reported runtime version is compatible.';

  @override
  String get runtimeReasonVersionIncompatible =>
      'The reported runtime version is incompatible.';

  @override
  String get runtimeReasonVersionUnverified =>
      'The runtime version could not be verified.';

  @override
  String get runtimeReasonEvidenceIncomplete =>
      'Some runtime health evidence is incomplete.';

  @override
  String get runtimeReasonOwnershipRequired =>
      'GixGiz ownership is required for this operation.';

  @override
  String get runtimeReasonConsentRequired =>
      'Explicit permission is required for this capability.';

  @override
  String get runtimeReasonOperationUnsupported =>
      'This runtime operation is not supported.';

  @override
  String get runtimeReasonProcessExited =>
      'The managed runtime process exited before it became ready.';

  @override
  String get runtimeReasonUnknown =>
      'Additional runtime evidence is not recognized by this GixGiz version.';

  @override
  String get runtimeWarningExternalInstallation =>
      'This runtime is installed and managed outside GixGiz.';

  @override
  String get runtimeWarningEndpointExposure =>
      'The runtime endpoint may be exposed beyond this device.';

  @override
  String get runtimeWarningVersionUntested =>
      'This runtime version has not been verified with this GixGiz release.';

  @override
  String get runtimeWarningPartialEvidence =>
      'Only partial runtime evidence is available.';

  @override
  String get runtimeWarningModelInventoryTruncated =>
      'The installed model list was limited for safe display.';

  @override
  String get runtimeWarningUnknown =>
      'An unrecognized runtime warning was reported.';

  @override
  String runtimeRecommendedAction(String action) {
    return 'Recommended action: $action';
  }

  @override
  String get runtimeRecoveryRetry => 'Try the operation again.';

  @override
  String get runtimeRecoveryRestart =>
      'Restart GixGiz, then check the runtime again.';

  @override
  String get runtimeRecoveryCheckPrerequisites =>
      'Check the runtime prerequisites, then try again.';

  @override
  String get runtimeRecoveryContactSupport =>
      'Contact support with the diagnostic code.';

  @override
  String get runtimeRecoveryNoAction => 'No action is required.';

  @override
  String get runtimeRecoveryUnknown =>
      'Review diagnostics before trying again.';

  @override
  String get runtimeProgressSemanticLabel => 'Runtime operation progress';

  @override
  String runtimeStatusSemanticLabel(
    String status,
    String message,
    String ownership,
    String consent,
  ) {
    return 'Runtime status: $status. $message Ownership: $ownership. Permission: $consent.';
  }

  @override
  String runtimeDetailsSemanticLabel(
    String provider,
    String version,
    String endpoint,
    String ownership,
    String reuseConsent,
    String managementConsent,
  ) {
    return 'Runtime details: $provider, version $version, endpoint $endpoint, ownership $ownership, reuse permission $reuseConsent, management permission $managementConsent.';
  }
}
